// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.14.0
// source: github.com/paralin/go-steam/protocol/protobuf/app_ticket.proto

package protobuf

import (
	base64 "encoding/base64"
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
)

type EncryptedAppTicket struct {
	unknownFields                 []byte
	TicketVersionNo               *uint32 `protobuf:"varint,1,opt,name=ticket_version_no,json=ticketVersionNo" json:"ticketVersionNo,omitempty"`
	CrcEncryptedticket            *uint32 `protobuf:"varint,2,opt,name=crc_encryptedticket,json=crcEncryptedticket" json:"crcEncryptedticket,omitempty"`
	CbEncrypteduserdata           *uint32 `protobuf:"varint,3,opt,name=cb_encrypteduserdata,json=cbEncrypteduserdata" json:"cbEncrypteduserdata,omitempty"`
	CbEncryptedAppownershipticket *uint32 `protobuf:"varint,4,opt,name=cb_encrypted_appownershipticket,json=cbEncryptedAppownershipticket" json:"cbEncryptedAppownershipticket,omitempty"`
	EncryptedTicket               []byte  `protobuf:"bytes,5,opt,name=encrypted_ticket,json=encryptedTicket" json:"encryptedTicket,omitempty"`
}

func (x *EncryptedAppTicket) Reset() {
	*x = EncryptedAppTicket{}
}

func (*EncryptedAppTicket) ProtoMessage() {}

func (x *EncryptedAppTicket) GetTicketVersionNo() uint32 {
	if x != nil && x.TicketVersionNo != nil {
		return *x.TicketVersionNo
	}
	return 0
}

func (x *EncryptedAppTicket) GetCrcEncryptedticket() uint32 {
	if x != nil && x.CrcEncryptedticket != nil {
		return *x.CrcEncryptedticket
	}
	return 0
}

func (x *EncryptedAppTicket) GetCbEncrypteduserdata() uint32 {
	if x != nil && x.CbEncrypteduserdata != nil {
		return *x.CbEncrypteduserdata
	}
	return 0
}

func (x *EncryptedAppTicket) GetCbEncryptedAppownershipticket() uint32 {
	if x != nil && x.CbEncryptedAppownershipticket != nil {
		return *x.CbEncryptedAppownershipticket
	}
	return 0
}

func (x *EncryptedAppTicket) GetEncryptedTicket() []byte {
	if x != nil {
		return x.EncryptedTicket
	}
	return nil
}

func (m *EncryptedAppTicket) CloneVT() *EncryptedAppTicket {
	if m == nil {
		return (*EncryptedAppTicket)(nil)
	}
	r := new(EncryptedAppTicket)
	if rhs := m.TicketVersionNo; rhs != nil {
		tmpVal := *rhs
		r.TicketVersionNo = &tmpVal
	}
	if rhs := m.CrcEncryptedticket; rhs != nil {
		tmpVal := *rhs
		r.CrcEncryptedticket = &tmpVal
	}
	if rhs := m.CbEncrypteduserdata; rhs != nil {
		tmpVal := *rhs
		r.CbEncrypteduserdata = &tmpVal
	}
	if rhs := m.CbEncryptedAppownershipticket; rhs != nil {
		tmpVal := *rhs
		r.CbEncryptedAppownershipticket = &tmpVal
	}
	if rhs := m.EncryptedTicket; rhs != nil {
		r.EncryptedTicket = slices.Clone(rhs)
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *EncryptedAppTicket) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *EncryptedAppTicket) EqualVT(that *EncryptedAppTicket) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.TicketVersionNo, that.TicketVersionNo; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.CrcEncryptedticket, that.CrcEncryptedticket; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.CbEncrypteduserdata, that.CbEncrypteduserdata; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.CbEncryptedAppownershipticket, that.CbEncryptedAppownershipticket; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.EncryptedTicket, that.EncryptedTicket; (p == nil && q != nil) || (p != nil && q == nil) || string(p) != string(q) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *EncryptedAppTicket) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*EncryptedAppTicket)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *EncryptedAppTicket) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EncryptedAppTicket) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *EncryptedAppTicket) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.EncryptedTicket != nil {
		i -= len(m.EncryptedTicket)
		copy(dAtA[i:], m.EncryptedTicket)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(m.EncryptedTicket)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CbEncryptedAppownershipticket != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.CbEncryptedAppownershipticket))
		i--
		dAtA[i] = 0x20
	}
	if m.CbEncrypteduserdata != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.CbEncrypteduserdata))
		i--
		dAtA[i] = 0x18
	}
	if m.CrcEncryptedticket != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.CrcEncryptedticket))
		i--
		dAtA[i] = 0x10
	}
	if m.TicketVersionNo != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.TicketVersionNo))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EncryptedAppTicket) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TicketVersionNo != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.TicketVersionNo))
	}
	if m.CrcEncryptedticket != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.CrcEncryptedticket))
	}
	if m.CbEncrypteduserdata != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.CbEncrypteduserdata))
	}
	if m.CbEncryptedAppownershipticket != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.CbEncryptedAppownershipticket))
	}
	if m.EncryptedTicket != nil {
		l = len(m.EncryptedTicket)
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (x *EncryptedAppTicket) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("EncryptedAppTicket {")
	if x.TicketVersionNo != nil {
		if sb.Len() > 20 {
			sb.WriteString(" ")
		}
		sb.WriteString("ticket_version_no: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.TicketVersionNo), 10))
	}
	if x.CrcEncryptedticket != nil {
		if sb.Len() > 20 {
			sb.WriteString(" ")
		}
		sb.WriteString("crc_encryptedticket: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.CrcEncryptedticket), 10))
	}
	if x.CbEncrypteduserdata != nil {
		if sb.Len() > 20 {
			sb.WriteString(" ")
		}
		sb.WriteString("cb_encrypteduserdata: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.CbEncrypteduserdata), 10))
	}
	if x.CbEncryptedAppownershipticket != nil {
		if sb.Len() > 20 {
			sb.WriteString(" ")
		}
		sb.WriteString("cb_encrypted_appownershipticket: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.CbEncryptedAppownershipticket), 10))
	}
	if x.EncryptedTicket != nil {
		if sb.Len() > 20 {
			sb.WriteString(" ")
		}
		sb.WriteString("encrypted_ticket: ")
		sb.WriteString("\"")
		sb.WriteString(base64.StdEncoding.EncodeToString(x.EncryptedTicket))
		sb.WriteString("\"")
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *EncryptedAppTicket) String() string {
	return x.MarshalProtoText()
}

func (m *EncryptedAppTicket) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EncryptedAppTicket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EncryptedAppTicket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TicketVersionNo", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.TicketVersionNo = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CrcEncryptedticket", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.CrcEncryptedticket = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CbEncrypteduserdata", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.CbEncrypteduserdata = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CbEncryptedAppownershipticket", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.CbEncryptedAppownershipticket = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedTicket", wireType)
			}
			var byteLen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			byteLen = int(_v)
			if err != nil {
				return err
			}
			if byteLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedTicket = append(m.EncryptedTicket[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptedTicket == nil {
				m.EncryptedTicket = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
