// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.18.0
// source: github.com/paralin/go-steam/protocol/protobuf/unified/credentials.proto

package unified

import (
	fmt "fmt"
	io "io"
	slices "slices"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	protobuf "github.com/paralin/go-steam/protocol/protobuf"
)

type CCredentials_GetSteamGuardDetails_Request struct {
	unknownFields          []byte
	Webcookie              *string                 `protobuf:"bytes,2,opt,name=webcookie" json:"webcookie,omitempty"`
	TimestampMinimumWanted *uint32                 `protobuf:"fixed32,3,opt,name=timestamp_minimum_wanted,json=timestampMinimumWanted" json:"timestampMinimumWanted,omitempty"`
	DeprecatedIpaddress    *int32                  `protobuf:"varint,4,opt,name=deprecated_ipaddress,json=deprecatedIpaddress" json:"deprecatedIpaddress,omitempty"`
	IpAddress              *protobuf.CMsgIPAddress `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress" json:"ipAddress,omitempty"`
}

func (x *CCredentials_GetSteamGuardDetails_Request) Reset() {
	*x = CCredentials_GetSteamGuardDetails_Request{}
}

func (*CCredentials_GetSteamGuardDetails_Request) ProtoMessage() {}

func (x *CCredentials_GetSteamGuardDetails_Request) GetWebcookie() string {
	if x != nil && x.Webcookie != nil {
		return *x.Webcookie
	}
	return ""
}

func (x *CCredentials_GetSteamGuardDetails_Request) GetTimestampMinimumWanted() uint32 {
	if x != nil && x.TimestampMinimumWanted != nil {
		return *x.TimestampMinimumWanted
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Request) GetDeprecatedIpaddress() int32 {
	if x != nil && x.DeprecatedIpaddress != nil {
		return *x.DeprecatedIpaddress
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Request) GetIpAddress() *protobuf.CMsgIPAddress {
	if x != nil {
		return x.IpAddress
	}
	return nil
}

type CCredentials_GetSteamGuardDetails_Response struct {
	unknownFields                                         []byte
	IsSteamguardEnabled                                   *bool                                                     `protobuf:"varint,1,opt,name=is_steamguard_enabled,json=isSteamguardEnabled" json:"isSteamguardEnabled,omitempty"`
	TimestampSteamguardEnabled                            *uint32                                                   `protobuf:"fixed32,2,opt,name=timestamp_steamguard_enabled,json=timestampSteamguardEnabled" json:"timestampSteamguardEnabled,omitempty"`
	DeprecatedMachineNameUserchosen                       *string                                                   `protobuf:"bytes,4,opt,name=deprecated_machine_name_userchosen,json=deprecatedMachineNameUserchosen" json:"deprecatedMachineNameUserchosen,omitempty"`
	DeprecatedTimestampMachineSteamguardEnabled           *uint32                                                   `protobuf:"fixed32,5,opt,name=deprecated_timestamp_machine_steamguard_enabled,json=deprecatedTimestampMachineSteamguardEnabled" json:"deprecatedTimestampMachineSteamguardEnabled,omitempty"`
	DeprecatedAuthenticationExistsFromGeolocBeforeMintime *bool                                                     `protobuf:"varint,6,opt,name=deprecated_authentication_exists_from_geoloc_before_mintime,json=deprecatedAuthenticationExistsFromGeolocBeforeMintime" json:"deprecatedAuthenticationExistsFromGeolocBeforeMintime,omitempty"`
	DeprecatedMachineId                                   *uint64                                                   `protobuf:"varint,7,opt,name=deprecated_machine_id,json=deprecatedMachineId" json:"deprecatedMachineId,omitempty"`
	SessionData                                           []*CCredentials_GetSteamGuardDetails_Response_SessionData `protobuf:"bytes,8,rep,name=session_data,json=sessionData" json:"sessionData,omitempty"`
	IsTwofactorEnabled                                    *bool                                                     `protobuf:"varint,9,opt,name=is_twofactor_enabled,json=isTwofactorEnabled" json:"isTwofactorEnabled,omitempty"`
	TimestampTwofactorEnabled                             *uint32                                                   `protobuf:"fixed32,10,opt,name=timestamp_twofactor_enabled,json=timestampTwofactorEnabled" json:"timestampTwofactorEnabled,omitempty"`
	IsPhoneVerified                                       *bool                                                     `protobuf:"varint,11,opt,name=is_phone_verified,json=isPhoneVerified" json:"isPhoneVerified,omitempty"`
}

func (x *CCredentials_GetSteamGuardDetails_Response) Reset() {
	*x = CCredentials_GetSteamGuardDetails_Response{}
}

func (*CCredentials_GetSteamGuardDetails_Response) ProtoMessage() {}

func (x *CCredentials_GetSteamGuardDetails_Response) GetIsSteamguardEnabled() bool {
	if x != nil && x.IsSteamguardEnabled != nil {
		return *x.IsSteamguardEnabled
	}
	return false
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetTimestampSteamguardEnabled() uint32 {
	if x != nil && x.TimestampSteamguardEnabled != nil {
		return *x.TimestampSteamguardEnabled
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedMachineNameUserchosen() string {
	if x != nil && x.DeprecatedMachineNameUserchosen != nil {
		return *x.DeprecatedMachineNameUserchosen
	}
	return ""
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedTimestampMachineSteamguardEnabled() uint32 {
	if x != nil && x.DeprecatedTimestampMachineSteamguardEnabled != nil {
		return *x.DeprecatedTimestampMachineSteamguardEnabled
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedAuthenticationExistsFromGeolocBeforeMintime() bool {
	if x != nil && x.DeprecatedAuthenticationExistsFromGeolocBeforeMintime != nil {
		return *x.DeprecatedAuthenticationExistsFromGeolocBeforeMintime
	}
	return false
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedMachineId() uint64 {
	if x != nil && x.DeprecatedMachineId != nil {
		return *x.DeprecatedMachineId
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetSessionData() []*CCredentials_GetSteamGuardDetails_Response_SessionData {
	if x != nil {
		return x.SessionData
	}
	return nil
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetIsTwofactorEnabled() bool {
	if x != nil && x.IsTwofactorEnabled != nil {
		return *x.IsTwofactorEnabled
	}
	return false
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetTimestampTwofactorEnabled() uint32 {
	if x != nil && x.TimestampTwofactorEnabled != nil {
		return *x.TimestampTwofactorEnabled
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Response) GetIsPhoneVerified() bool {
	if x != nil && x.IsPhoneVerified != nil {
		return *x.IsPhoneVerified
	}
	return false
}

type CCredentials_ValidateEmailAddress_Request struct {
	unknownFields []byte
	Stoken        *string `protobuf:"bytes,1,opt,name=stoken" json:"stoken,omitempty"`
}

func (x *CCredentials_ValidateEmailAddress_Request) Reset() {
	*x = CCredentials_ValidateEmailAddress_Request{}
}

func (*CCredentials_ValidateEmailAddress_Request) ProtoMessage() {}

func (x *CCredentials_ValidateEmailAddress_Request) GetStoken() string {
	if x != nil && x.Stoken != nil {
		return *x.Stoken
	}
	return ""
}

type CCredentials_ValidateEmailAddress_Response struct {
	unknownFields []byte
	WasValidated  *bool `protobuf:"varint,1,opt,name=was_validated,json=wasValidated" json:"wasValidated,omitempty"`
}

func (x *CCredentials_ValidateEmailAddress_Response) Reset() {
	*x = CCredentials_ValidateEmailAddress_Response{}
}

func (*CCredentials_ValidateEmailAddress_Response) ProtoMessage() {}

func (x *CCredentials_ValidateEmailAddress_Response) GetWasValidated() bool {
	if x != nil && x.WasValidated != nil {
		return *x.WasValidated
	}
	return false
}

type CCredentials_SteamGuardPhishingReport_Request struct {
	unknownFields   []byte
	ParamString     *string `protobuf:"bytes,1,opt,name=param_string,json=paramString" json:"paramString,omitempty"`
	IpaddressActual *string `protobuf:"bytes,2,opt,name=ipaddress_actual,json=ipaddressActual" json:"ipaddressActual,omitempty"`
}

func (x *CCredentials_SteamGuardPhishingReport_Request) Reset() {
	*x = CCredentials_SteamGuardPhishingReport_Request{}
}

func (*CCredentials_SteamGuardPhishingReport_Request) ProtoMessage() {}

func (x *CCredentials_SteamGuardPhishingReport_Request) GetParamString() string {
	if x != nil && x.ParamString != nil {
		return *x.ParamString
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Request) GetIpaddressActual() string {
	if x != nil && x.IpaddressActual != nil {
		return *x.IpaddressActual
	}
	return ""
}

type CCredentials_SteamGuardPhishingReport_Response struct {
	unknownFields           []byte
	IpaddressLoginattempt   *string `protobuf:"bytes,1,opt,name=ipaddress_loginattempt,json=ipaddressLoginattempt" json:"ipaddressLoginattempt,omitempty"`
	CountrynameLoginattempt *string `protobuf:"bytes,2,opt,name=countryname_loginattempt,json=countrynameLoginattempt" json:"countrynameLoginattempt,omitempty"`
	StatenameLoginattempt   *string `protobuf:"bytes,3,opt,name=statename_loginattempt,json=statenameLoginattempt" json:"statenameLoginattempt,omitempty"`
	CitynameLoginattempt    *string `protobuf:"bytes,4,opt,name=cityname_loginattempt,json=citynameLoginattempt" json:"citynameLoginattempt,omitempty"`
	IpaddressActual         *string `protobuf:"bytes,5,opt,name=ipaddress_actual,json=ipaddressActual" json:"ipaddressActual,omitempty"`
	CountrynameActual       *string `protobuf:"bytes,6,opt,name=countryname_actual,json=countrynameActual" json:"countrynameActual,omitempty"`
	StatenameActual         *string `protobuf:"bytes,7,opt,name=statename_actual,json=statenameActual" json:"statenameActual,omitempty"`
	CitynameActual          *string `protobuf:"bytes,8,opt,name=cityname_actual,json=citynameActual" json:"citynameActual,omitempty"`
	SteamguardCode          *string `protobuf:"bytes,9,opt,name=steamguard_code,json=steamguardCode" json:"steamguardCode,omitempty"`
}

func (x *CCredentials_SteamGuardPhishingReport_Response) Reset() {
	*x = CCredentials_SteamGuardPhishingReport_Response{}
}

func (*CCredentials_SteamGuardPhishingReport_Response) ProtoMessage() {}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetIpaddressLoginattempt() string {
	if x != nil && x.IpaddressLoginattempt != nil {
		return *x.IpaddressLoginattempt
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetCountrynameLoginattempt() string {
	if x != nil && x.CountrynameLoginattempt != nil {
		return *x.CountrynameLoginattempt
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetStatenameLoginattempt() string {
	if x != nil && x.StatenameLoginattempt != nil {
		return *x.StatenameLoginattempt
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetCitynameLoginattempt() string {
	if x != nil && x.CitynameLoginattempt != nil {
		return *x.CitynameLoginattempt
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetIpaddressActual() string {
	if x != nil && x.IpaddressActual != nil {
		return *x.IpaddressActual
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetCountrynameActual() string {
	if x != nil && x.CountrynameActual != nil {
		return *x.CountrynameActual
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetStatenameActual() string {
	if x != nil && x.StatenameActual != nil {
		return *x.StatenameActual
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetCitynameActual() string {
	if x != nil && x.CitynameActual != nil {
		return *x.CitynameActual
	}
	return ""
}

func (x *CCredentials_SteamGuardPhishingReport_Response) GetSteamguardCode() string {
	if x != nil && x.SteamguardCode != nil {
		return *x.SteamguardCode
	}
	return ""
}

type CCredentials_LastCredentialChangeTime_Request struct {
	unknownFields   []byte
	UserChangesOnly *bool `protobuf:"varint,1,opt,name=user_changes_only,json=userChangesOnly" json:"userChangesOnly,omitempty"`
}

func (x *CCredentials_LastCredentialChangeTime_Request) Reset() {
	*x = CCredentials_LastCredentialChangeTime_Request{}
}

func (*CCredentials_LastCredentialChangeTime_Request) ProtoMessage() {}

func (x *CCredentials_LastCredentialChangeTime_Request) GetUserChangesOnly() bool {
	if x != nil && x.UserChangesOnly != nil {
		return *x.UserChangesOnly
	}
	return false
}

type CCredentials_LastCredentialChangeTime_Response struct {
	unknownFields               []byte
	TimestampLastPasswordChange *uint32 `protobuf:"fixed32,1,opt,name=timestamp_last_password_change,json=timestampLastPasswordChange" json:"timestampLastPasswordChange,omitempty"`
	TimestampLastEmailChange    *uint32 `protobuf:"fixed32,2,opt,name=timestamp_last_email_change,json=timestampLastEmailChange" json:"timestampLastEmailChange,omitempty"`
	TimestampLastPasswordReset  *uint32 `protobuf:"fixed32,3,opt,name=timestamp_last_password_reset,json=timestampLastPasswordReset" json:"timestampLastPasswordReset,omitempty"`
}

func (x *CCredentials_LastCredentialChangeTime_Response) Reset() {
	*x = CCredentials_LastCredentialChangeTime_Response{}
}

func (*CCredentials_LastCredentialChangeTime_Response) ProtoMessage() {}

func (x *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastPasswordChange() uint32 {
	if x != nil && x.TimestampLastPasswordChange != nil {
		return *x.TimestampLastPasswordChange
	}
	return 0
}

func (x *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastEmailChange() uint32 {
	if x != nil && x.TimestampLastEmailChange != nil {
		return *x.TimestampLastEmailChange
	}
	return 0
}

func (x *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastPasswordReset() uint32 {
	if x != nil && x.TimestampLastPasswordReset != nil {
		return *x.TimestampLastPasswordReset
	}
	return 0
}

type CCredentials_GetAccountAuthSecret_Request struct {
	unknownFields []byte
}

func (x *CCredentials_GetAccountAuthSecret_Request) Reset() {
	*x = CCredentials_GetAccountAuthSecret_Request{}
}

func (*CCredentials_GetAccountAuthSecret_Request) ProtoMessage() {}

type CCredentials_GetAccountAuthSecret_Response struct {
	unknownFields []byte
	SecretId      *int32 `protobuf:"varint,1,opt,name=secret_id,json=secretId" json:"secretId,omitempty"`
	Secret        []byte `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
}

func (x *CCredentials_GetAccountAuthSecret_Response) Reset() {
	*x = CCredentials_GetAccountAuthSecret_Response{}
}

func (*CCredentials_GetAccountAuthSecret_Response) ProtoMessage() {}

func (x *CCredentials_GetAccountAuthSecret_Response) GetSecretId() int32 {
	if x != nil && x.SecretId != nil {
		return *x.SecretId
	}
	return 0
}

func (x *CCredentials_GetAccountAuthSecret_Response) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type CCredentials_GetSteamGuardDetails_Response_SessionData struct {
	unknownFields                               []byte
	MachineId                                   *uint64 `protobuf:"varint,1,opt,name=machine_id,json=machineId" json:"machineId,omitempty"`
	MachineNameUserchosen                       *string `protobuf:"bytes,2,opt,name=machine_name_userchosen,json=machineNameUserchosen" json:"machineNameUserchosen,omitempty"`
	TimestampMachineSteamguardEnabled           *uint32 `protobuf:"fixed32,3,opt,name=timestamp_machine_steamguard_enabled,json=timestampMachineSteamguardEnabled" json:"timestampMachineSteamguardEnabled,omitempty"`
	AuthenticationExistsFromGeolocBeforeMintime *bool   `protobuf:"varint,4,opt,name=authentication_exists_from_geoloc_before_mintime,json=authenticationExistsFromGeolocBeforeMintime" json:"authenticationExistsFromGeolocBeforeMintime,omitempty"`
	AuthenticationExistsFromSameIpBeforeMintime *bool   `protobuf:"varint,6,opt,name=authentication_exists_from_same_ip_before_mintime,json=authenticationExistsFromSameIpBeforeMintime" json:"authenticationExistsFromSameIpBeforeMintime,omitempty"`
	PublicIpv4                                  *uint32 `protobuf:"varint,7,opt,name=public_ipv4,json=publicIpv4" json:"publicIpv4,omitempty"`
	PublicIpAddress                             *string `protobuf:"bytes,8,opt,name=public_ip_address,json=publicIpAddress" json:"publicIpAddress,omitempty"`
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) Reset() {
	*x = CCredentials_GetSteamGuardDetails_Response_SessionData{}
}

func (*CCredentials_GetSteamGuardDetails_Response_SessionData) ProtoMessage() {}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) GetMachineId() uint64 {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) GetMachineNameUserchosen() string {
	if x != nil && x.MachineNameUserchosen != nil {
		return *x.MachineNameUserchosen
	}
	return ""
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) GetTimestampMachineSteamguardEnabled() uint32 {
	if x != nil && x.TimestampMachineSteamguardEnabled != nil {
		return *x.TimestampMachineSteamguardEnabled
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) GetAuthenticationExistsFromGeolocBeforeMintime() bool {
	if x != nil && x.AuthenticationExistsFromGeolocBeforeMintime != nil {
		return *x.AuthenticationExistsFromGeolocBeforeMintime
	}
	return false
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) GetAuthenticationExistsFromSameIpBeforeMintime() bool {
	if x != nil && x.AuthenticationExistsFromSameIpBeforeMintime != nil {
		return *x.AuthenticationExistsFromSameIpBeforeMintime
	}
	return false
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) GetPublicIpv4() uint32 {
	if x != nil && x.PublicIpv4 != nil {
		return *x.PublicIpv4
	}
	return 0
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) GetPublicIpAddress() string {
	if x != nil && x.PublicIpAddress != nil {
		return *x.PublicIpAddress
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Request) CloneVT() *CCredentials_GetSteamGuardDetails_Request {
	if m == nil {
		return (*CCredentials_GetSteamGuardDetails_Request)(nil)
	}
	r := new(CCredentials_GetSteamGuardDetails_Request)
	r.Webcookie = protobuf_go_lite.ClonePtr(m.Webcookie)
	r.TimestampMinimumWanted = protobuf_go_lite.ClonePtr(m.TimestampMinimumWanted)
	r.DeprecatedIpaddress = protobuf_go_lite.ClonePtr(m.DeprecatedIpaddress)
	r.IpAddress = protobuf_go_lite.CloneVTValue(m.IpAddress)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_GetSteamGuardDetails_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) CloneVT() *CCredentials_GetSteamGuardDetails_Response_SessionData {
	if m == nil {
		return (*CCredentials_GetSteamGuardDetails_Response_SessionData)(nil)
	}
	r := new(CCredentials_GetSteamGuardDetails_Response_SessionData)
	r.MachineId = protobuf_go_lite.ClonePtr(m.MachineId)
	r.MachineNameUserchosen = protobuf_go_lite.ClonePtr(m.MachineNameUserchosen)
	r.TimestampMachineSteamguardEnabled = protobuf_go_lite.ClonePtr(m.TimestampMachineSteamguardEnabled)
	r.AuthenticationExistsFromGeolocBeforeMintime = protobuf_go_lite.ClonePtr(m.AuthenticationExistsFromGeolocBeforeMintime)
	r.AuthenticationExistsFromSameIpBeforeMintime = protobuf_go_lite.ClonePtr(m.AuthenticationExistsFromSameIpBeforeMintime)
	r.PublicIpv4 = protobuf_go_lite.ClonePtr(m.PublicIpv4)
	r.PublicIpAddress = protobuf_go_lite.ClonePtr(m.PublicIpAddress)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_GetSteamGuardDetails_Response) CloneVT() *CCredentials_GetSteamGuardDetails_Response {
	if m == nil {
		return (*CCredentials_GetSteamGuardDetails_Response)(nil)
	}
	r := new(CCredentials_GetSteamGuardDetails_Response)
	r.IsSteamguardEnabled = protobuf_go_lite.ClonePtr(m.IsSteamguardEnabled)
	r.TimestampSteamguardEnabled = protobuf_go_lite.ClonePtr(m.TimestampSteamguardEnabled)
	r.DeprecatedMachineNameUserchosen = protobuf_go_lite.ClonePtr(m.DeprecatedMachineNameUserchosen)
	r.DeprecatedTimestampMachineSteamguardEnabled = protobuf_go_lite.ClonePtr(m.DeprecatedTimestampMachineSteamguardEnabled)
	r.DeprecatedAuthenticationExistsFromGeolocBeforeMintime = protobuf_go_lite.ClonePtr(m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime)
	r.DeprecatedMachineId = protobuf_go_lite.ClonePtr(m.DeprecatedMachineId)
	r.SessionData = protobuf_go_lite.CloneVTSlice(m.SessionData)
	r.IsTwofactorEnabled = protobuf_go_lite.ClonePtr(m.IsTwofactorEnabled)
	r.TimestampTwofactorEnabled = protobuf_go_lite.ClonePtr(m.TimestampTwofactorEnabled)
	r.IsPhoneVerified = protobuf_go_lite.ClonePtr(m.IsPhoneVerified)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_GetSteamGuardDetails_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_ValidateEmailAddress_Request) CloneVT() *CCredentials_ValidateEmailAddress_Request {
	if m == nil {
		return (*CCredentials_ValidateEmailAddress_Request)(nil)
	}
	r := new(CCredentials_ValidateEmailAddress_Request)
	r.Stoken = protobuf_go_lite.ClonePtr(m.Stoken)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_ValidateEmailAddress_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_ValidateEmailAddress_Response) CloneVT() *CCredentials_ValidateEmailAddress_Response {
	if m == nil {
		return (*CCredentials_ValidateEmailAddress_Response)(nil)
	}
	r := new(CCredentials_ValidateEmailAddress_Response)
	r.WasValidated = protobuf_go_lite.ClonePtr(m.WasValidated)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_ValidateEmailAddress_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_SteamGuardPhishingReport_Request) CloneVT() *CCredentials_SteamGuardPhishingReport_Request {
	if m == nil {
		return (*CCredentials_SteamGuardPhishingReport_Request)(nil)
	}
	r := new(CCredentials_SteamGuardPhishingReport_Request)
	r.ParamString = protobuf_go_lite.ClonePtr(m.ParamString)
	r.IpaddressActual = protobuf_go_lite.ClonePtr(m.IpaddressActual)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_SteamGuardPhishingReport_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_SteamGuardPhishingReport_Response) CloneVT() *CCredentials_SteamGuardPhishingReport_Response {
	if m == nil {
		return (*CCredentials_SteamGuardPhishingReport_Response)(nil)
	}
	r := new(CCredentials_SteamGuardPhishingReport_Response)
	r.IpaddressLoginattempt = protobuf_go_lite.ClonePtr(m.IpaddressLoginattempt)
	r.CountrynameLoginattempt = protobuf_go_lite.ClonePtr(m.CountrynameLoginattempt)
	r.StatenameLoginattempt = protobuf_go_lite.ClonePtr(m.StatenameLoginattempt)
	r.CitynameLoginattempt = protobuf_go_lite.ClonePtr(m.CitynameLoginattempt)
	r.IpaddressActual = protobuf_go_lite.ClonePtr(m.IpaddressActual)
	r.CountrynameActual = protobuf_go_lite.ClonePtr(m.CountrynameActual)
	r.StatenameActual = protobuf_go_lite.ClonePtr(m.StatenameActual)
	r.CitynameActual = protobuf_go_lite.ClonePtr(m.CitynameActual)
	r.SteamguardCode = protobuf_go_lite.ClonePtr(m.SteamguardCode)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_SteamGuardPhishingReport_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_LastCredentialChangeTime_Request) CloneVT() *CCredentials_LastCredentialChangeTime_Request {
	if m == nil {
		return (*CCredentials_LastCredentialChangeTime_Request)(nil)
	}
	r := new(CCredentials_LastCredentialChangeTime_Request)
	r.UserChangesOnly = protobuf_go_lite.ClonePtr(m.UserChangesOnly)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_LastCredentialChangeTime_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_LastCredentialChangeTime_Response) CloneVT() *CCredentials_LastCredentialChangeTime_Response {
	if m == nil {
		return (*CCredentials_LastCredentialChangeTime_Response)(nil)
	}
	r := new(CCredentials_LastCredentialChangeTime_Response)
	r.TimestampLastPasswordChange = protobuf_go_lite.ClonePtr(m.TimestampLastPasswordChange)
	r.TimestampLastEmailChange = protobuf_go_lite.ClonePtr(m.TimestampLastEmailChange)
	r.TimestampLastPasswordReset = protobuf_go_lite.ClonePtr(m.TimestampLastPasswordReset)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_LastCredentialChangeTime_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_GetAccountAuthSecret_Request) CloneVT() *CCredentials_GetAccountAuthSecret_Request {
	if m == nil {
		return (*CCredentials_GetAccountAuthSecret_Request)(nil)
	}
	r := new(CCredentials_GetAccountAuthSecret_Request)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_GetAccountAuthSecret_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CCredentials_GetAccountAuthSecret_Response) CloneVT() *CCredentials_GetAccountAuthSecret_Response {
	if m == nil {
		return (*CCredentials_GetAccountAuthSecret_Response)(nil)
	}
	r := new(CCredentials_GetAccountAuthSecret_Response)
	r.SecretId = protobuf_go_lite.ClonePtr(m.SecretId)
	r.Secret = protobuf_go_lite.CloneBytes(m.Secret)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CCredentials_GetAccountAuthSecret_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *CCredentials_GetSteamGuardDetails_Request) EqualVT(that *CCredentials_GetSteamGuardDetails_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Webcookie, that.Webcookie) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TimestampMinimumWanted, that.TimestampMinimumWanted) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DeprecatedIpaddress, that.DeprecatedIpaddress) {
		return false
	}
	if !protobuf_go_lite.IsEqualVT(this.IpAddress, that.IpAddress) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_GetSteamGuardDetails_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_GetSteamGuardDetails_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_GetSteamGuardDetails_Response_SessionData) EqualVT(that *CCredentials_GetSteamGuardDetails_Response_SessionData) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.MachineId, that.MachineId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.MachineNameUserchosen, that.MachineNameUserchosen) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TimestampMachineSteamguardEnabled, that.TimestampMachineSteamguardEnabled) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AuthenticationExistsFromGeolocBeforeMintime, that.AuthenticationExistsFromGeolocBeforeMintime) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AuthenticationExistsFromSameIpBeforeMintime, that.AuthenticationExistsFromSameIpBeforeMintime) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.PublicIpv4, that.PublicIpv4) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.PublicIpAddress, that.PublicIpAddress) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_GetSteamGuardDetails_Response_SessionData) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_GetSteamGuardDetails_Response_SessionData)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_GetSteamGuardDetails_Response) EqualVT(that *CCredentials_GetSteamGuardDetails_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.IsSteamguardEnabled, that.IsSteamguardEnabled) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TimestampSteamguardEnabled, that.TimestampSteamguardEnabled) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DeprecatedMachineNameUserchosen, that.DeprecatedMachineNameUserchosen) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DeprecatedTimestampMachineSteamguardEnabled, that.DeprecatedTimestampMachineSteamguardEnabled) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DeprecatedAuthenticationExistsFromGeolocBeforeMintime, that.DeprecatedAuthenticationExistsFromGeolocBeforeMintime) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DeprecatedMachineId, that.DeprecatedMachineId) {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.SessionData, that.SessionData, func() *CCredentials_GetSteamGuardDetails_Response_SessionData {
		return &CCredentials_GetSteamGuardDetails_Response_SessionData{}
	}) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.IsTwofactorEnabled, that.IsTwofactorEnabled) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TimestampTwofactorEnabled, that.TimestampTwofactorEnabled) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.IsPhoneVerified, that.IsPhoneVerified) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_GetSteamGuardDetails_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_GetSteamGuardDetails_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_ValidateEmailAddress_Request) EqualVT(that *CCredentials_ValidateEmailAddress_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Stoken, that.Stoken) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_ValidateEmailAddress_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_ValidateEmailAddress_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_ValidateEmailAddress_Response) EqualVT(that *CCredentials_ValidateEmailAddress_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.WasValidated, that.WasValidated) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_ValidateEmailAddress_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_ValidateEmailAddress_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_SteamGuardPhishingReport_Request) EqualVT(that *CCredentials_SteamGuardPhishingReport_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.ParamString, that.ParamString) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.IpaddressActual, that.IpaddressActual) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_SteamGuardPhishingReport_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_SteamGuardPhishingReport_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_SteamGuardPhishingReport_Response) EqualVT(that *CCredentials_SteamGuardPhishingReport_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.IpaddressLoginattempt, that.IpaddressLoginattempt) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.CountrynameLoginattempt, that.CountrynameLoginattempt) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.StatenameLoginattempt, that.StatenameLoginattempt) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.CitynameLoginattempt, that.CitynameLoginattempt) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.IpaddressActual, that.IpaddressActual) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.CountrynameActual, that.CountrynameActual) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.StatenameActual, that.StatenameActual) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.CitynameActual, that.CitynameActual) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.SteamguardCode, that.SteamguardCode) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_SteamGuardPhishingReport_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_SteamGuardPhishingReport_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_LastCredentialChangeTime_Request) EqualVT(that *CCredentials_LastCredentialChangeTime_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.UserChangesOnly, that.UserChangesOnly) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_LastCredentialChangeTime_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_LastCredentialChangeTime_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_LastCredentialChangeTime_Response) EqualVT(that *CCredentials_LastCredentialChangeTime_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TimestampLastPasswordChange, that.TimestampLastPasswordChange) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TimestampLastEmailChange, that.TimestampLastEmailChange) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.TimestampLastPasswordReset, that.TimestampLastPasswordReset) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_LastCredentialChangeTime_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_LastCredentialChangeTime_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_GetAccountAuthSecret_Request) EqualVT(that *CCredentials_GetAccountAuthSecret_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_GetAccountAuthSecret_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_GetAccountAuthSecret_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CCredentials_GetAccountAuthSecret_Response) EqualVT(that *CCredentials_GetAccountAuthSecret_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.SecretId, that.SecretId) {
		return false
	}
	if !protobuf_go_lite.EqualBytesPresent(this.Secret, that.Secret) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CCredentials_GetAccountAuthSecret_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CCredentials_GetAccountAuthSecret_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *CCredentials_GetSteamGuardDetails_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_GetSteamGuardDetails_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_GetSteamGuardDetails_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.IpAddress != nil {
		size, err := m.IpAddress.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if m.DeprecatedIpaddress != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.DeprecatedIpaddress))
		i--
		dAtA[i] = 0x20
	}
	if m.TimestampMinimumWanted != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.TimestampMinimumWanted))
		i--
		dAtA[i] = 0x1d
	}
	if m.Webcookie != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.Webcookie)
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.PublicIpAddress != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.PublicIpAddress)
		i--
		dAtA[i] = 0x42
	}
	if m.PublicIpv4 != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.PublicIpv4))
		i--
		dAtA[i] = 0x38
	}
	if m.AuthenticationExistsFromSameIpBeforeMintime != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.AuthenticationExistsFromSameIpBeforeMintime)
		i--
		dAtA[i] = 0x30
	}
	if m.AuthenticationExistsFromGeolocBeforeMintime != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.AuthenticationExistsFromGeolocBeforeMintime)
		i--
		dAtA[i] = 0x20
	}
	if m.TimestampMachineSteamguardEnabled != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.TimestampMachineSteamguardEnabled))
		i--
		dAtA[i] = 0x1d
	}
	if m.MachineNameUserchosen != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.MachineNameUserchosen)
		i--
		dAtA[i] = 0x12
	}
	if m.MachineId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.MachineId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_GetSteamGuardDetails_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_GetSteamGuardDetails_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_GetSteamGuardDetails_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.IsPhoneVerified != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.IsPhoneVerified)
		i--
		dAtA[i] = 0x58
	}
	if m.TimestampTwofactorEnabled != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.TimestampTwofactorEnabled))
		i--
		dAtA[i] = 0x55
	}
	if m.IsTwofactorEnabled != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.IsTwofactorEnabled)
		i--
		dAtA[i] = 0x48
	}
	if len(m.SessionData) > 0 {
		for iNdEx := len(m.SessionData) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.SessionData[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.DeprecatedMachineId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.DeprecatedMachineId))
		i--
		dAtA[i] = 0x38
	}
	if m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime)
		i--
		dAtA[i] = 0x30
	}
	if m.DeprecatedTimestampMachineSteamguardEnabled != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.DeprecatedTimestampMachineSteamguardEnabled))
		i--
		dAtA[i] = 0x2d
	}
	if m.DeprecatedMachineNameUserchosen != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.DeprecatedMachineNameUserchosen)
		i--
		dAtA[i] = 0x22
	}
	if m.TimestampSteamguardEnabled != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.TimestampSteamguardEnabled))
		i--
		dAtA[i] = 0x15
	}
	if m.IsSteamguardEnabled != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.IsSteamguardEnabled)
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_ValidateEmailAddress_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_ValidateEmailAddress_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_ValidateEmailAddress_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Stoken != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.Stoken)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_ValidateEmailAddress_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_ValidateEmailAddress_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_ValidateEmailAddress_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.WasValidated != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.WasValidated)
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_SteamGuardPhishingReport_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_SteamGuardPhishingReport_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_SteamGuardPhishingReport_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.IpaddressActual != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.IpaddressActual)
		i--
		dAtA[i] = 0x12
	}
	if m.ParamString != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.ParamString)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_SteamGuardPhishingReport_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_SteamGuardPhishingReport_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_SteamGuardPhishingReport_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.SteamguardCode != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.SteamguardCode)
		i--
		dAtA[i] = 0x4a
	}
	if m.CitynameActual != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.CitynameActual)
		i--
		dAtA[i] = 0x42
	}
	if m.StatenameActual != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.StatenameActual)
		i--
		dAtA[i] = 0x3a
	}
	if m.CountrynameActual != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.CountrynameActual)
		i--
		dAtA[i] = 0x32
	}
	if m.IpaddressActual != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.IpaddressActual)
		i--
		dAtA[i] = 0x2a
	}
	if m.CitynameLoginattempt != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.CitynameLoginattempt)
		i--
		dAtA[i] = 0x22
	}
	if m.StatenameLoginattempt != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.StatenameLoginattempt)
		i--
		dAtA[i] = 0x1a
	}
	if m.CountrynameLoginattempt != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.CountrynameLoginattempt)
		i--
		dAtA[i] = 0x12
	}
	if m.IpaddressLoginattempt != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.IpaddressLoginattempt)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_LastCredentialChangeTime_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_LastCredentialChangeTime_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_LastCredentialChangeTime_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.UserChangesOnly != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.UserChangesOnly)
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_LastCredentialChangeTime_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_LastCredentialChangeTime_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_LastCredentialChangeTime_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.TimestampLastPasswordReset != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.TimestampLastPasswordReset))
		i--
		dAtA[i] = 0x1d
	}
	if m.TimestampLastEmailChange != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.TimestampLastEmailChange))
		i--
		dAtA[i] = 0x15
	}
	if m.TimestampLastPasswordChange != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.TimestampLastPasswordChange))
		i--
		dAtA[i] = 0xd
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_GetAccountAuthSecret_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_GetAccountAuthSecret_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_GetAccountAuthSecret_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_GetAccountAuthSecret_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCredentials_GetAccountAuthSecret_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CCredentials_GetAccountAuthSecret_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Secret != nil {
		i = protobuf_go_lite.EncodeBytes(dAtA, i, m.Secret)
		i--
		dAtA[i] = 0x12
	}
	if m.SecretId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.SecretId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CCredentials_GetSteamGuardDetails_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.Webcookie)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.TimestampMinimumWanted)
	n += protobuf_go_lite.SizeVarintPtr(1, m.DeprecatedIpaddress)
	if m.IpAddress != nil {
		l = m.IpAddress.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.MachineId)
	n += protobuf_go_lite.SizeStringPtr(1, m.MachineNameUserchosen)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.TimestampMachineSteamguardEnabled)
	n += protobuf_go_lite.SizeBoolPtr(1, m.AuthenticationExistsFromGeolocBeforeMintime)
	n += protobuf_go_lite.SizeBoolPtr(1, m.AuthenticationExistsFromSameIpBeforeMintime)
	n += protobuf_go_lite.SizeVarintPtr(1, m.PublicIpv4)
	n += protobuf_go_lite.SizeStringPtr(1, m.PublicIpAddress)
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_GetSteamGuardDetails_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolPtr(1, m.IsSteamguardEnabled)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.TimestampSteamguardEnabled)
	n += protobuf_go_lite.SizeStringPtr(1, m.DeprecatedMachineNameUserchosen)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.DeprecatedTimestampMachineSteamguardEnabled)
	n += protobuf_go_lite.SizeBoolPtr(1, m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime)
	n += protobuf_go_lite.SizeVarintPtr(1, m.DeprecatedMachineId)
	for _, e := range m.SessionData {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += protobuf_go_lite.SizeBoolPtr(1, m.IsTwofactorEnabled)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.TimestampTwofactorEnabled)
	n += protobuf_go_lite.SizeBoolPtr(1, m.IsPhoneVerified)
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_ValidateEmailAddress_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.Stoken)
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_ValidateEmailAddress_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolPtr(1, m.WasValidated)
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_SteamGuardPhishingReport_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.ParamString)
	n += protobuf_go_lite.SizeStringPtr(1, m.IpaddressActual)
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_SteamGuardPhishingReport_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.IpaddressLoginattempt)
	n += protobuf_go_lite.SizeStringPtr(1, m.CountrynameLoginattempt)
	n += protobuf_go_lite.SizeStringPtr(1, m.StatenameLoginattempt)
	n += protobuf_go_lite.SizeStringPtr(1, m.CitynameLoginattempt)
	n += protobuf_go_lite.SizeStringPtr(1, m.IpaddressActual)
	n += protobuf_go_lite.SizeStringPtr(1, m.CountrynameActual)
	n += protobuf_go_lite.SizeStringPtr(1, m.StatenameActual)
	n += protobuf_go_lite.SizeStringPtr(1, m.CitynameActual)
	n += protobuf_go_lite.SizeStringPtr(1, m.SteamguardCode)
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_LastCredentialChangeTime_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeBoolPtr(1, m.UserChangesOnly)
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_LastCredentialChangeTime_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.TimestampLastPasswordChange)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.TimestampLastEmailChange)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.TimestampLastPasswordReset)
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_GetAccountAuthSecret_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += len(m.unknownFields)
	return n
}

func (m *CCredentials_GetAccountAuthSecret_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.SecretId)
	n += protobuf_go_lite.SizeBytesPresent(1, m.Secret)
	n += len(m.unknownFields)
	return n
}

func (x *CCredentials_GetSteamGuardDetails_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_GetSteamGuardDetails_Request")
	if x.Webcookie != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "webcookie")
		protobuf_go_lite.TextWriteString(&sb, *x.Webcookie)
	}
	if x.TimestampMinimumWanted != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp_minimum_wanted")
		protobuf_go_lite.TextWriteUint(&sb, *x.TimestampMinimumWanted)
	}
	if x.DeprecatedIpaddress != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "deprecated_ipaddress")
		protobuf_go_lite.TextWriteInt(&sb, *x.DeprecatedIpaddress)
	}
	if x.IpAddress != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "ip_address")
		protobuf_go_lite.TextWriteTextMarshaler(&sb, x.IpAddress)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_GetSteamGuardDetails_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "SessionData")
	if x.MachineId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "machine_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.MachineId)
	}
	if x.MachineNameUserchosen != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "machine_name_userchosen")
		protobuf_go_lite.TextWriteString(&sb, *x.MachineNameUserchosen)
	}
	if x.TimestampMachineSteamguardEnabled != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp_machine_steamguard_enabled")
		protobuf_go_lite.TextWriteUint(&sb, *x.TimestampMachineSteamguardEnabled)
	}
	if x.AuthenticationExistsFromGeolocBeforeMintime != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "authentication_exists_from_geoloc_before_mintime")
		protobuf_go_lite.TextWriteBool(&sb, *x.AuthenticationExistsFromGeolocBeforeMintime)
	}
	if x.AuthenticationExistsFromSameIpBeforeMintime != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "authentication_exists_from_same_ip_before_mintime")
		protobuf_go_lite.TextWriteBool(&sb, *x.AuthenticationExistsFromSameIpBeforeMintime)
	}
	if x.PublicIpv4 != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "public_ipv4")
		protobuf_go_lite.TextWriteUint(&sb, *x.PublicIpv4)
	}
	if x.PublicIpAddress != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "public_ip_address")
		protobuf_go_lite.TextWriteString(&sb, *x.PublicIpAddress)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_GetSteamGuardDetails_Response_SessionData) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_GetSteamGuardDetails_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_GetSteamGuardDetails_Response")
	if x.IsSteamguardEnabled != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "is_steamguard_enabled")
		protobuf_go_lite.TextWriteBool(&sb, *x.IsSteamguardEnabled)
	}
	if x.TimestampSteamguardEnabled != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp_steamguard_enabled")
		protobuf_go_lite.TextWriteUint(&sb, *x.TimestampSteamguardEnabled)
	}
	if x.DeprecatedMachineNameUserchosen != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "deprecated_machine_name_userchosen")
		protobuf_go_lite.TextWriteString(&sb, *x.DeprecatedMachineNameUserchosen)
	}
	if x.DeprecatedTimestampMachineSteamguardEnabled != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "deprecated_timestamp_machine_steamguard_enabled")
		protobuf_go_lite.TextWriteUint(&sb, *x.DeprecatedTimestampMachineSteamguardEnabled)
	}
	if x.DeprecatedAuthenticationExistsFromGeolocBeforeMintime != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "deprecated_authentication_exists_from_geoloc_before_mintime")
		protobuf_go_lite.TextWriteBool(&sb, *x.DeprecatedAuthenticationExistsFromGeolocBeforeMintime)
	}
	if x.DeprecatedMachineId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "deprecated_machine_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.DeprecatedMachineId)
	}
	if len(x.SessionData) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "session_data")
		for i, v := range x.SessionData {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &CCredentials_GetSteamGuardDetails_Response_SessionData{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	if x.IsTwofactorEnabled != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "is_twofactor_enabled")
		protobuf_go_lite.TextWriteBool(&sb, *x.IsTwofactorEnabled)
	}
	if x.TimestampTwofactorEnabled != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp_twofactor_enabled")
		protobuf_go_lite.TextWriteUint(&sb, *x.TimestampTwofactorEnabled)
	}
	if x.IsPhoneVerified != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "is_phone_verified")
		protobuf_go_lite.TextWriteBool(&sb, *x.IsPhoneVerified)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_GetSteamGuardDetails_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_ValidateEmailAddress_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_ValidateEmailAddress_Request")
	if x.Stoken != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "stoken")
		protobuf_go_lite.TextWriteString(&sb, *x.Stoken)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_ValidateEmailAddress_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_ValidateEmailAddress_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_ValidateEmailAddress_Response")
	if x.WasValidated != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "was_validated")
		protobuf_go_lite.TextWriteBool(&sb, *x.WasValidated)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_ValidateEmailAddress_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_SteamGuardPhishingReport_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_SteamGuardPhishingReport_Request")
	if x.ParamString != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "param_string")
		protobuf_go_lite.TextWriteString(&sb, *x.ParamString)
	}
	if x.IpaddressActual != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "ipaddress_actual")
		protobuf_go_lite.TextWriteString(&sb, *x.IpaddressActual)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_SteamGuardPhishingReport_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_SteamGuardPhishingReport_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_SteamGuardPhishingReport_Response")
	if x.IpaddressLoginattempt != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "ipaddress_loginattempt")
		protobuf_go_lite.TextWriteString(&sb, *x.IpaddressLoginattempt)
	}
	if x.CountrynameLoginattempt != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "countryname_loginattempt")
		protobuf_go_lite.TextWriteString(&sb, *x.CountrynameLoginattempt)
	}
	if x.StatenameLoginattempt != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "statename_loginattempt")
		protobuf_go_lite.TextWriteString(&sb, *x.StatenameLoginattempt)
	}
	if x.CitynameLoginattempt != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "cityname_loginattempt")
		protobuf_go_lite.TextWriteString(&sb, *x.CitynameLoginattempt)
	}
	if x.IpaddressActual != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "ipaddress_actual")
		protobuf_go_lite.TextWriteString(&sb, *x.IpaddressActual)
	}
	if x.CountrynameActual != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "countryname_actual")
		protobuf_go_lite.TextWriteString(&sb, *x.CountrynameActual)
	}
	if x.StatenameActual != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "statename_actual")
		protobuf_go_lite.TextWriteString(&sb, *x.StatenameActual)
	}
	if x.CitynameActual != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "cityname_actual")
		protobuf_go_lite.TextWriteString(&sb, *x.CitynameActual)
	}
	if x.SteamguardCode != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "steamguard_code")
		protobuf_go_lite.TextWriteString(&sb, *x.SteamguardCode)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_SteamGuardPhishingReport_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_LastCredentialChangeTime_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_LastCredentialChangeTime_Request")
	if x.UserChangesOnly != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "user_changes_only")
		protobuf_go_lite.TextWriteBool(&sb, *x.UserChangesOnly)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_LastCredentialChangeTime_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_LastCredentialChangeTime_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_LastCredentialChangeTime_Response")
	if x.TimestampLastPasswordChange != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp_last_password_change")
		protobuf_go_lite.TextWriteUint(&sb, *x.TimestampLastPasswordChange)
	}
	if x.TimestampLastEmailChange != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp_last_email_change")
		protobuf_go_lite.TextWriteUint(&sb, *x.TimestampLastEmailChange)
	}
	if x.TimestampLastPasswordReset != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp_last_password_reset")
		protobuf_go_lite.TextWriteUint(&sb, *x.TimestampLastPasswordReset)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_LastCredentialChangeTime_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_GetAccountAuthSecret_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	protobuf_go_lite.TextStartMessage(&sb, "CCredentials_GetAccountAuthSecret_Request")
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_GetAccountAuthSecret_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CCredentials_GetAccountAuthSecret_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CCredentials_GetAccountAuthSecret_Response")
	if x.SecretId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "secret_id")
		protobuf_go_lite.TextWriteInt(&sb, *x.SecretId)
	}
	if x.Secret != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "secret")
		protobuf_go_lite.TextWriteBytes(&sb, x.Secret)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CCredentials_GetAccountAuthSecret_Response) String() string {
	return x.MarshalProtoText()
}

func (m *CCredentials_GetSteamGuardDetails_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_GetSteamGuardDetails_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_GetSteamGuardDetails_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Webcookie", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Webcookie = &v
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampMinimumWanted", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.TimestampMinimumWanted = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedIpaddress", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DeprecatedIpaddress = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpAddress", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			if m.IpAddress == nil {
				m.IpAddress = &protobuf.CMsgIPAddress{}
			}
			if err := m.IpAddress.UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_GetSteamGuardDetails_Response_SessionData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_GetSteamGuardDetails_Response_SessionData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MachineId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.MachineId = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MachineNameUserchosen", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.MachineNameUserchosen = &v
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampMachineSteamguardEnabled", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.TimestampMachineSteamguardEnabled = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticationExistsFromGeolocBeforeMintime", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.AuthenticationExistsFromGeolocBeforeMintime = &b
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticationExistsFromSameIpBeforeMintime", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.AuthenticationExistsFromSameIpBeforeMintime = &b
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicIpv4", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.PublicIpv4 = &v
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicIpAddress", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.PublicIpAddress = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_GetSteamGuardDetails_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_GetSteamGuardDetails_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_GetSteamGuardDetails_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSteamguardEnabled", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.IsSteamguardEnabled = &b
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampSteamguardEnabled", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.TimestampSteamguardEnabled = &v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedMachineNameUserchosen", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DeprecatedMachineNameUserchosen = &v
		case 5:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedTimestampMachineSteamguardEnabled", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.DeprecatedTimestampMachineSteamguardEnabled = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedAuthenticationExistsFromGeolocBeforeMintime", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime = &b
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedMachineId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DeprecatedMachineId = &v
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionData", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SessionData = append(m.SessionData, &CCredentials_GetSteamGuardDetails_Response_SessionData{})
			if err := m.SessionData[len(m.SessionData)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsTwofactorEnabled", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.IsTwofactorEnabled = &b
		case 10:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampTwofactorEnabled", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.TimestampTwofactorEnabled = &v
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPhoneVerified", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.IsPhoneVerified = &b
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_ValidateEmailAddress_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_ValidateEmailAddress_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_ValidateEmailAddress_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stoken", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Stoken = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_ValidateEmailAddress_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_ValidateEmailAddress_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_ValidateEmailAddress_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasValidated", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.WasValidated = &b
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_SteamGuardPhishingReport_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_SteamGuardPhishingReport_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_SteamGuardPhishingReport_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamString", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ParamString = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpaddressActual", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.IpaddressActual = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_SteamGuardPhishingReport_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_SteamGuardPhishingReport_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_SteamGuardPhishingReport_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpaddressLoginattempt", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.IpaddressLoginattempt = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountrynameLoginattempt", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.CountrynameLoginattempt = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatenameLoginattempt", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.StatenameLoginattempt = &v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CitynameLoginattempt", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.CitynameLoginattempt = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpaddressActual", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.IpaddressActual = &v
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountrynameActual", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.CountrynameActual = &v
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatenameActual", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.StatenameActual = &v
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CitynameActual", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.CitynameActual = &v
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteamguardCode", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SteamguardCode = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_LastCredentialChangeTime_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_LastCredentialChangeTime_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_LastCredentialChangeTime_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserChangesOnly", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.UserChangesOnly = &b
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_LastCredentialChangeTime_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_LastCredentialChangeTime_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_LastCredentialChangeTime_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampLastPasswordChange", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.TimestampLastPasswordChange = &v
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampLastEmailChange", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.TimestampLastEmailChange = &v
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampLastPasswordReset", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.TimestampLastPasswordReset = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_GetAccountAuthSecret_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_GetAccountAuthSecret_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_GetAccountAuthSecret_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CCredentials_GetAccountAuthSecret_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCredentials_GetAccountAuthSecret_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCredentials_GetAccountAuthSecret_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretId", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SecretId = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Secret", wireType)
			}
			m.Secret, iNdEx, err = protobuf_go_lite.DecodeBytesAppend(m.Secret, dAtA, iNdEx)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
