// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_offline.steamclient.proto

package unified

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/paralin/go-steam/protocol/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type COffline_GetOfflineLogonTicket_Request struct {
	Priority             *uint32  `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	PerformEncryption    *bool    `protobuf:"varint,2,opt,name=perform_encryption,json=performEncryption" json:"perform_encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *COffline_GetOfflineLogonTicket_Request) Reset() {
	*m = COffline_GetOfflineLogonTicket_Request{}
}
func (m *COffline_GetOfflineLogonTicket_Request) String() string { return proto.CompactTextString(m) }
func (*COffline_GetOfflineLogonTicket_Request) ProtoMessage()    {}
func (*COffline_GetOfflineLogonTicket_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_86478a2284c871a9, []int{0}
}

func (m *COffline_GetOfflineLogonTicket_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_COffline_GetOfflineLogonTicket_Request.Unmarshal(m, b)
}
func (m *COffline_GetOfflineLogonTicket_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_COffline_GetOfflineLogonTicket_Request.Marshal(b, m, deterministic)
}
func (m *COffline_GetOfflineLogonTicket_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_COffline_GetOfflineLogonTicket_Request.Merge(m, src)
}
func (m *COffline_GetOfflineLogonTicket_Request) XXX_Size() int {
	return xxx_messageInfo_COffline_GetOfflineLogonTicket_Request.Size(m)
}
func (m *COffline_GetOfflineLogonTicket_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_COffline_GetOfflineLogonTicket_Request.DiscardUnknown(m)
}

var xxx_messageInfo_COffline_GetOfflineLogonTicket_Request proto.InternalMessageInfo

func (m *COffline_GetOfflineLogonTicket_Request) GetPriority() uint32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *COffline_GetOfflineLogonTicket_Request) GetPerformEncryption() bool {
	if m != nil && m.PerformEncryption != nil {
		return *m.PerformEncryption
	}
	return false
}

type COffline_GetOfflineLogonTicket_Response struct {
	SerializedTicket     []byte          `protobuf:"bytes,1,opt,name=serialized_ticket,json=serializedTicket" json:"serialized_ticket,omitempty"`
	Signature            []byte          `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	EncryptedTicket      *Offline_Ticket `protobuf:"bytes,3,opt,name=encrypted_ticket,json=encryptedTicket" json:"encrypted_ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *COffline_GetOfflineLogonTicket_Response) Reset() {
	*m = COffline_GetOfflineLogonTicket_Response{}
}
func (m *COffline_GetOfflineLogonTicket_Response) String() string { return proto.CompactTextString(m) }
func (*COffline_GetOfflineLogonTicket_Response) ProtoMessage()    {}
func (*COffline_GetOfflineLogonTicket_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_86478a2284c871a9, []int{1}
}

func (m *COffline_GetOfflineLogonTicket_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_COffline_GetOfflineLogonTicket_Response.Unmarshal(m, b)
}
func (m *COffline_GetOfflineLogonTicket_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_COffline_GetOfflineLogonTicket_Response.Marshal(b, m, deterministic)
}
func (m *COffline_GetOfflineLogonTicket_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_COffline_GetOfflineLogonTicket_Response.Merge(m, src)
}
func (m *COffline_GetOfflineLogonTicket_Response) XXX_Size() int {
	return xxx_messageInfo_COffline_GetOfflineLogonTicket_Response.Size(m)
}
func (m *COffline_GetOfflineLogonTicket_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_COffline_GetOfflineLogonTicket_Response.DiscardUnknown(m)
}

var xxx_messageInfo_COffline_GetOfflineLogonTicket_Response proto.InternalMessageInfo

func (m *COffline_GetOfflineLogonTicket_Response) GetSerializedTicket() []byte {
	if m != nil {
		return m.SerializedTicket
	}
	return nil
}

func (m *COffline_GetOfflineLogonTicket_Response) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *COffline_GetOfflineLogonTicket_Response) GetEncryptedTicket() *Offline_Ticket {
	if m != nil {
		return m.EncryptedTicket
	}
	return nil
}

type COffline_GetUnsignedOfflineLogonTicket_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) Reset() {
	*m = COffline_GetUnsignedOfflineLogonTicket_Request{}
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Request) String() string {
	return proto.CompactTextString(m)
}
func (*COffline_GetUnsignedOfflineLogonTicket_Request) ProtoMessage() {}
func (*COffline_GetUnsignedOfflineLogonTicket_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_86478a2284c871a9, []int{2}
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Request.Unmarshal(m, b)
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Request.Marshal(b, m, deterministic)
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Request.Merge(m, src)
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Request) XXX_Size() int {
	return xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Request.Size(m)
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Request.DiscardUnknown(m)
}

var xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Request proto.InternalMessageInfo

type COffline_OfflineLogonTicket struct {
	Accountid            *uint32  `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Rtime32CreationTime  *uint32  `protobuf:"fixed32,2,opt,name=rtime32_creation_time,json=rtime32CreationTime" json:"rtime32_creation_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *COffline_OfflineLogonTicket) Reset()         { *m = COffline_OfflineLogonTicket{} }
func (m *COffline_OfflineLogonTicket) String() string { return proto.CompactTextString(m) }
func (*COffline_OfflineLogonTicket) ProtoMessage()    {}
func (*COffline_OfflineLogonTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_86478a2284c871a9, []int{3}
}

func (m *COffline_OfflineLogonTicket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_COffline_OfflineLogonTicket.Unmarshal(m, b)
}
func (m *COffline_OfflineLogonTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_COffline_OfflineLogonTicket.Marshal(b, m, deterministic)
}
func (m *COffline_OfflineLogonTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_COffline_OfflineLogonTicket.Merge(m, src)
}
func (m *COffline_OfflineLogonTicket) XXX_Size() int {
	return xxx_messageInfo_COffline_OfflineLogonTicket.Size(m)
}
func (m *COffline_OfflineLogonTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_COffline_OfflineLogonTicket.DiscardUnknown(m)
}

var xxx_messageInfo_COffline_OfflineLogonTicket proto.InternalMessageInfo

func (m *COffline_OfflineLogonTicket) GetAccountid() uint32 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

func (m *COffline_OfflineLogonTicket) GetRtime32CreationTime() uint32 {
	if m != nil && m.Rtime32CreationTime != nil {
		return *m.Rtime32CreationTime
	}
	return 0
}

type COffline_GetUnsignedOfflineLogonTicket_Response struct {
	Ticket               *COffline_OfflineLogonTicket `protobuf:"bytes,1,opt,name=ticket" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) Reset() {
	*m = COffline_GetUnsignedOfflineLogonTicket_Response{}
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Response) String() string {
	return proto.CompactTextString(m)
}
func (*COffline_GetUnsignedOfflineLogonTicket_Response) ProtoMessage() {}
func (*COffline_GetUnsignedOfflineLogonTicket_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_86478a2284c871a9, []int{4}
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Response.Unmarshal(m, b)
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Response.Marshal(b, m, deterministic)
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Response.Merge(m, src)
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Response) XXX_Size() int {
	return xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Response.Size(m)
}
func (m *COffline_GetUnsignedOfflineLogonTicket_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Response.DiscardUnknown(m)
}

var xxx_messageInfo_COffline_GetUnsignedOfflineLogonTicket_Response proto.InternalMessageInfo

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) GetTicket() *COffline_OfflineLogonTicket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func init() {
	proto.RegisterType((*COffline_GetOfflineLogonTicket_Request)(nil), "COffline_GetOfflineLogonTicket_Request")
	proto.RegisterType((*COffline_GetOfflineLogonTicket_Response)(nil), "COffline_GetOfflineLogonTicket_Response")
	proto.RegisterType((*COffline_GetUnsignedOfflineLogonTicket_Request)(nil), "COffline_GetUnsignedOfflineLogonTicket_Request")
	proto.RegisterType((*COffline_OfflineLogonTicket)(nil), "COffline_OfflineLogonTicket")
	proto.RegisterType((*COffline_GetUnsignedOfflineLogonTicket_Response)(nil), "COffline_GetUnsignedOfflineLogonTicket_Response")
}

func init() {
	proto.RegisterFile("steammessages_offline.steamclient.proto", fileDescriptor_86478a2284c871a9)
}

var fileDescriptor_86478a2284c871a9 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xd1, 0xab, 0xd3, 0x30,
	0x14, 0xc6, 0x89, 0x17, 0xbc, 0xd7, 0x73, 0x27, 0xdb, 0xa2, 0x83, 0x51, 0x27, 0x8c, 0x3e, 0xb8,
	0x82, 0x9a, 0x8d, 0xea, 0x93, 0x8f, 0x0e, 0xf1, 0x45, 0x10, 0xc2, 0x7c, 0x2e, 0xb5, 0x3d, 0x2d,
	0xd1, 0x35, 0xa9, 0x49, 0xfa, 0x30, 0x9f, 0xc4, 0xbf, 0xc8, 0xbf, 0xcf, 0x27, 0x69, 0x1b, 0xdb,
	0x8d, 0xe9, 0xee, 0xf6, 0x96, 0x9c, 0xdf, 0x97, 0x73, 0xbe, 0x7c, 0x09, 0x2c, 0x8c, 0xc5, 0xb8,
	0x28, 0xd0, 0x98, 0x38, 0x47, 0x13, 0xa9, 0x2c, 0xdb, 0x0a, 0x89, 0xac, 0xa9, 0x26, 0x5b, 0x81,
	0xd2, 0xb2, 0x52, 0x2b, 0xab, 0xbc, 0xe9, 0xa1, 0xf0, 0x73, 0x6c, 0xd0, 0x91, 0x17, 0x87, 0xa4,
	0x92, 0x22, 0x13, 0x98, 0xb6, 0x8a, 0xe3, 0x3e, 0x8f, 0xdd, 0x88, 0xc8, 0x8a, 0xe4, 0x2b, 0xba,
	0xaa, 0x6f, 0xe0, 0xd9, 0xfa, 0xa3, 0x03, 0xef, 0xd1, 0xba, 0xe5, 0x07, 0x95, 0x2b, 0xb9, 0x69,
	0x74, 0x11, 0xc7, 0x6f, 0x15, 0x1a, 0x4b, 0x3d, 0xb8, 0x29, 0xb5, 0x50, 0x5a, 0xd8, 0xdd, 0x94,
	0xcc, 0x49, 0xf0, 0x90, 0x77, 0x7b, 0xfa, 0x12, 0x68, 0x89, 0x3a, 0x53, 0xba, 0x88, 0x50, 0x26,
	0x7a, 0x57, 0x5a, 0xa1, 0xe4, 0xf4, 0xde, 0x9c, 0x04, 0x37, 0x7c, 0xec, 0xc8, 0xbb, 0x0e, 0xf8,
	0xbf, 0x08, 0x2c, 0xee, 0x9c, 0x6a, 0x4a, 0x25, 0x0d, 0xd2, 0xe7, 0x30, 0x36, 0xa8, 0x45, 0xbc,
	0x15, 0xdf, 0x31, 0x75, 0xde, 0x9b, 0xf9, 0x03, 0x3e, 0xea, 0x41, 0x7b, 0x8a, 0xce, 0xe0, 0x81,
	0x11, 0xb9, 0x8c, 0x6d, 0xa5, 0xb1, 0x19, 0x3f, 0xe0, 0x7d, 0x81, 0xbe, 0x81, 0x91, 0x73, 0xd7,
	0x77, 0xba, 0x9a, 0x93, 0xe0, 0x36, 0x1c, 0xb2, 0xbf, 0x6e, 0xda, 0x46, 0x7c, 0xd8, 0x09, 0xdb,
	0x82, 0xbf, 0x02, 0xb6, 0xef, 0xf8, 0x93, 0xac, 0xdb, 0x62, 0xfa, 0xff, 0xbc, 0x7c, 0x05, 0x4f,
	0xba, 0x13, 0xc7, 0xb2, 0xda, 0x6a, 0x9c, 0x24, 0xaa, 0x92, 0x56, 0xa4, 0x2e, 0xcf, 0xbe, 0x40,
	0x43, 0x98, 0x68, 0x2b, 0x0a, 0x7c, 0x15, 0x46, 0x89, 0xc6, 0xb8, 0x4e, 0x2d, 0xaa, 0xf7, 0xcd,
	0xa5, 0xae, 0xf9, 0x23, 0x07, 0xd7, 0x8e, 0x6d, 0x44, 0x81, 0x7e, 0x0e, 0xcb, 0xb3, 0x2d, 0xba,
	0x70, 0x5f, 0xc3, 0xfd, 0xbd, 0x44, 0x6f, 0xc3, 0x19, 0x3b, 0x61, 0x99, 0x3b, 0x6d, 0xf8, 0x9b,
	0xc0, 0xb5, 0xc3, 0xf4, 0x0b, 0x4c, 0xfe, 0xf9, 0x80, 0x74, 0xc1, 0xce, 0xfb, 0x57, 0x5e, 0xc0,
	0xce, 0xfd, 0x0a, 0x3f, 0x09, 0x3c, 0x3d, 0x79, 0x31, 0xba, 0xbc, 0xf0, 0x91, 0xbc, 0x15, 0xbb,
	0x30, 0xb2, 0xb7, 0x57, 0x3f, 0x08, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x90, 0x2a, 0x1c, 0x52,
	0xbd, 0x03, 0x00, 0x00,
}
