// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.14.0
// source: github.com/paralin/go-steam/protocol/protobuf/unified/offline.proto

package unified

import (
	base64 "encoding/base64"
	binary "encoding/binary"
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	_ "github.com/paralin/go-steam/protocol/protobuf"
)

type COffline_GetOfflineLogonTicket_Request struct {
	unknownFields     []byte
	Priority          *uint32 `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	PerformEncryption *bool   `protobuf:"varint,2,opt,name=perform_encryption,json=performEncryption" json:"performEncryption,omitempty"`
}

func (x *COffline_GetOfflineLogonTicket_Request) Reset() {
	*x = COffline_GetOfflineLogonTicket_Request{}
}

func (*COffline_GetOfflineLogonTicket_Request) ProtoMessage() {}

func (x *COffline_GetOfflineLogonTicket_Request) GetPriority() uint32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *COffline_GetOfflineLogonTicket_Request) GetPerformEncryption() bool {
	if x != nil && x.PerformEncryption != nil {
		return *x.PerformEncryption
	}
	return false
}

type COffline_GetOfflineLogonTicket_Response struct {
	unknownFields    []byte
	SerializedTicket []byte          `protobuf:"bytes,1,opt,name=serialized_ticket,json=serializedTicket" json:"serializedTicket,omitempty"`
	Signature        []byte          `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	EncryptedTicket  *Offline_Ticket `protobuf:"bytes,3,opt,name=encrypted_ticket,json=encryptedTicket" json:"encryptedTicket,omitempty"`
}

func (x *COffline_GetOfflineLogonTicket_Response) Reset() {
	*x = COffline_GetOfflineLogonTicket_Response{}
}

func (*COffline_GetOfflineLogonTicket_Response) ProtoMessage() {}

func (x *COffline_GetOfflineLogonTicket_Response) GetSerializedTicket() []byte {
	if x != nil {
		return x.SerializedTicket
	}
	return nil
}

func (x *COffline_GetOfflineLogonTicket_Response) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *COffline_GetOfflineLogonTicket_Response) GetEncryptedTicket() *Offline_Ticket {
	if x != nil {
		return x.EncryptedTicket
	}
	return nil
}

type COffline_GetUnsignedOfflineLogonTicket_Request struct {
	unknownFields []byte
}

func (x *COffline_GetUnsignedOfflineLogonTicket_Request) Reset() {
	*x = COffline_GetUnsignedOfflineLogonTicket_Request{}
}

func (*COffline_GetUnsignedOfflineLogonTicket_Request) ProtoMessage() {}

type COffline_OfflineLogonTicket struct {
	unknownFields       []byte
	Accountid           *uint32 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Rtime32CreationTime *uint32 `protobuf:"fixed32,2,opt,name=rtime32_creation_time,json=rtime32CreationTime" json:"rtime32CreationTime,omitempty"`
}

func (x *COffline_OfflineLogonTicket) Reset() {
	*x = COffline_OfflineLogonTicket{}
}

func (*COffline_OfflineLogonTicket) ProtoMessage() {}

func (x *COffline_OfflineLogonTicket) GetAccountid() uint32 {
	if x != nil && x.Accountid != nil {
		return *x.Accountid
	}
	return 0
}

func (x *COffline_OfflineLogonTicket) GetRtime32CreationTime() uint32 {
	if x != nil && x.Rtime32CreationTime != nil {
		return *x.Rtime32CreationTime
	}
	return 0
}

type COffline_GetUnsignedOfflineLogonTicket_Response struct {
	unknownFields []byte
	Ticket        *COffline_OfflineLogonTicket `protobuf:"bytes,1,opt,name=ticket" json:"ticket,omitempty"`
}

func (x *COffline_GetUnsignedOfflineLogonTicket_Response) Reset() {
	*x = COffline_GetUnsignedOfflineLogonTicket_Response{}
}

func (*COffline_GetUnsignedOfflineLogonTicket_Response) ProtoMessage() {}

func (x *COffline_GetUnsignedOfflineLogonTicket_Response) GetTicket() *COffline_OfflineLogonTicket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (m *COffline_GetOfflineLogonTicket_Request) CloneVT() *COffline_GetOfflineLogonTicket_Request {
	if m == nil {
		return (*COffline_GetOfflineLogonTicket_Request)(nil)
	}
	r := new(COffline_GetOfflineLogonTicket_Request)
	if rhs := m.Priority; rhs != nil {
		tmpVal := *rhs
		r.Priority = &tmpVal
	}
	if rhs := m.PerformEncryption; rhs != nil {
		tmpVal := *rhs
		r.PerformEncryption = &tmpVal
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *COffline_GetOfflineLogonTicket_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *COffline_GetOfflineLogonTicket_Response) CloneVT() *COffline_GetOfflineLogonTicket_Response {
	if m == nil {
		return (*COffline_GetOfflineLogonTicket_Response)(nil)
	}
	r := new(COffline_GetOfflineLogonTicket_Response)
	r.EncryptedTicket = m.EncryptedTicket.CloneVT()
	if rhs := m.SerializedTicket; rhs != nil {
		r.SerializedTicket = slices.Clone(rhs)
	}
	if rhs := m.Signature; rhs != nil {
		r.Signature = slices.Clone(rhs)
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *COffline_GetOfflineLogonTicket_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) CloneVT() *COffline_GetUnsignedOfflineLogonTicket_Request {
	if m == nil {
		return (*COffline_GetUnsignedOfflineLogonTicket_Request)(nil)
	}
	r := new(COffline_GetUnsignedOfflineLogonTicket_Request)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *COffline_OfflineLogonTicket) CloneVT() *COffline_OfflineLogonTicket {
	if m == nil {
		return (*COffline_OfflineLogonTicket)(nil)
	}
	r := new(COffline_OfflineLogonTicket)
	if rhs := m.Accountid; rhs != nil {
		tmpVal := *rhs
		r.Accountid = &tmpVal
	}
	if rhs := m.Rtime32CreationTime; rhs != nil {
		tmpVal := *rhs
		r.Rtime32CreationTime = &tmpVal
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *COffline_OfflineLogonTicket) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) CloneVT() *COffline_GetUnsignedOfflineLogonTicket_Response {
	if m == nil {
		return (*COffline_GetUnsignedOfflineLogonTicket_Response)(nil)
	}
	r := new(COffline_GetUnsignedOfflineLogonTicket_Response)
	r.Ticket = m.Ticket.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *COffline_GetOfflineLogonTicket_Request) EqualVT(that *COffline_GetOfflineLogonTicket_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Priority, that.Priority; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.PerformEncryption, that.PerformEncryption; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *COffline_GetOfflineLogonTicket_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*COffline_GetOfflineLogonTicket_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *COffline_GetOfflineLogonTicket_Response) EqualVT(that *COffline_GetOfflineLogonTicket_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.SerializedTicket, that.SerializedTicket; (p == nil && q != nil) || (p != nil && q == nil) || string(p) != string(q) {
		return false
	}
	if p, q := this.Signature, that.Signature; (p == nil && q != nil) || (p != nil && q == nil) || string(p) != string(q) {
		return false
	}
	if !this.EncryptedTicket.EqualVT(that.EncryptedTicket) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *COffline_GetOfflineLogonTicket_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*COffline_GetOfflineLogonTicket_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *COffline_GetUnsignedOfflineLogonTicket_Request) EqualVT(that *COffline_GetUnsignedOfflineLogonTicket_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *COffline_GetUnsignedOfflineLogonTicket_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*COffline_GetUnsignedOfflineLogonTicket_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *COffline_OfflineLogonTicket) EqualVT(that *COffline_OfflineLogonTicket) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Accountid, that.Accountid; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Rtime32CreationTime, that.Rtime32CreationTime; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *COffline_OfflineLogonTicket) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*COffline_OfflineLogonTicket)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *COffline_GetUnsignedOfflineLogonTicket_Response) EqualVT(that *COffline_GetUnsignedOfflineLogonTicket_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.Ticket.EqualVT(that.Ticket) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *COffline_GetUnsignedOfflineLogonTicket_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*COffline_GetUnsignedOfflineLogonTicket_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *COffline_GetOfflineLogonTicket_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *COffline_GetOfflineLogonTicket_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *COffline_GetOfflineLogonTicket_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.PerformEncryption != nil {
		i--
		if *m.PerformEncryption {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Priority != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Priority))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *COffline_GetOfflineLogonTicket_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *COffline_GetOfflineLogonTicket_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *COffline_GetOfflineLogonTicket_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.EncryptedTicket != nil {
		size, err := m.EncryptedTicket.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.Signature != nil {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if m.SerializedTicket != nil {
		i -= len(m.SerializedTicket)
		copy(dAtA[i:], m.SerializedTicket)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(m.SerializedTicket)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	return len(dAtA) - i, nil
}

func (m *COffline_OfflineLogonTicket) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *COffline_OfflineLogonTicket) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *COffline_OfflineLogonTicket) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Rtime32CreationTime != nil {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(*m.Rtime32CreationTime))
		i--
		dAtA[i] = 0x15
	}
	if m.Accountid != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Accountid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Ticket != nil {
		size, err := m.Ticket.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *COffline_GetOfflineLogonTicket_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Priority != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Priority))
	}
	if m.PerformEncryption != nil {
		n += 2
	}
	n += len(m.unknownFields)
	return n
}

func (m *COffline_GetOfflineLogonTicket_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SerializedTicket != nil {
		l = len(m.SerializedTicket)
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.Signature != nil {
		l = len(m.Signature)
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	if m.EncryptedTicket != nil {
		l = m.EncryptedTicket.SizeVT()
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += len(m.unknownFields)
	return n
}

func (m *COffline_OfflineLogonTicket) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Accountid != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Accountid))
	}
	if m.Rtime32CreationTime != nil {
		n += 5
	}
	n += len(m.unknownFields)
	return n
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ticket != nil {
		l = m.Ticket.SizeVT()
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (x *COffline_GetOfflineLogonTicket_Request) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("COffline_GetOfflineLogonTicket_Request {")
	if x.Priority != nil {
		if sb.Len() > 40 {
			sb.WriteString(" ")
		}
		sb.WriteString("priority: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Priority), 10))
	}
	if x.PerformEncryption != nil {
		if sb.Len() > 40 {
			sb.WriteString(" ")
		}
		sb.WriteString("perform_encryption: ")
		sb.WriteString(strconv.FormatBool(*x.PerformEncryption))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *COffline_GetOfflineLogonTicket_Request) String() string {
	return x.MarshalProtoText()
}

func (x *COffline_GetOfflineLogonTicket_Response) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("COffline_GetOfflineLogonTicket_Response {")
	if x.SerializedTicket != nil {
		if sb.Len() > 41 {
			sb.WriteString(" ")
		}
		sb.WriteString("serialized_ticket: ")
		sb.WriteString("\"")
		sb.WriteString(base64.StdEncoding.EncodeToString(x.SerializedTicket))
		sb.WriteString("\"")
	}
	if x.Signature != nil {
		if sb.Len() > 41 {
			sb.WriteString(" ")
		}
		sb.WriteString("signature: ")
		sb.WriteString("\"")
		sb.WriteString(base64.StdEncoding.EncodeToString(x.Signature))
		sb.WriteString("\"")
	}
	if x.EncryptedTicket != nil {
		if sb.Len() > 41 {
			sb.WriteString(" ")
		}
		sb.WriteString("encrypted_ticket: ")
		sb.WriteString(x.EncryptedTicket.MarshalProtoText())
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *COffline_GetOfflineLogonTicket_Response) String() string {
	return x.MarshalProtoText()
}

func (x *COffline_GetUnsignedOfflineLogonTicket_Request) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("COffline_GetUnsignedOfflineLogonTicket_Request {")
	sb.WriteString("}")
	return sb.String()
}

func (x *COffline_GetUnsignedOfflineLogonTicket_Request) String() string {
	return x.MarshalProtoText()
}

func (x *COffline_OfflineLogonTicket) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("COffline_OfflineLogonTicket {")
	if x.Accountid != nil {
		if sb.Len() > 29 {
			sb.WriteString(" ")
		}
		sb.WriteString("accountid: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Accountid), 10))
	}
	if x.Rtime32CreationTime != nil {
		if sb.Len() > 29 {
			sb.WriteString(" ")
		}
		sb.WriteString("rtime32_creation_time: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Rtime32CreationTime), 10))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *COffline_OfflineLogonTicket) String() string {
	return x.MarshalProtoText()
}

func (x *COffline_GetUnsignedOfflineLogonTicket_Response) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("COffline_GetUnsignedOfflineLogonTicket_Response {")
	if x.Ticket != nil {
		if sb.Len() > 49 {
			sb.WriteString(" ")
		}
		sb.WriteString("ticket: ")
		sb.WriteString(x.Ticket.MarshalProtoText())
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *COffline_GetUnsignedOfflineLogonTicket_Response) String() string {
	return x.MarshalProtoText()
}

func (m *COffline_GetOfflineLogonTicket_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: COffline_GetOfflineLogonTicket_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: COffline_GetOfflineLogonTicket_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Priority = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerformEncryption", wireType)
			}
			var v int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = int(_v)
			if err != nil {
				return err
			}
			b := bool(v != 0)
			m.PerformEncryption = &b
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *COffline_GetOfflineLogonTicket_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: COffline_GetOfflineLogonTicket_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: COffline_GetOfflineLogonTicket_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SerializedTicket", wireType)
			}
			var byteLen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			byteLen = int(_v)
			if err != nil {
				return err
			}
			if byteLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SerializedTicket = append(m.SerializedTicket[:0], dAtA[iNdEx:postIndex]...)
			if m.SerializedTicket == nil {
				m.SerializedTicket = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			byteLen = int(_v)
			if err != nil {
				return err
			}
			if byteLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedTicket", wireType)
			}
			var msglen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			msglen = int(_v)
			if err != nil {
				return err
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EncryptedTicket == nil {
				m.EncryptedTicket = &Offline_Ticket{}
			}
			if err := m.EncryptedTicket.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: COffline_GetUnsignedOfflineLogonTicket_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: COffline_GetUnsignedOfflineLogonTicket_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *COffline_OfflineLogonTicket) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: COffline_OfflineLogonTicket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: COffline_OfflineLogonTicket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accountid", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Accountid = &v
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rtime32CreationTime", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Rtime32CreationTime = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *COffline_GetUnsignedOfflineLogonTicket_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: COffline_GetUnsignedOfflineLogonTicket_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: COffline_GetUnsignedOfflineLogonTicket_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ticket", wireType)
			}
			var msglen int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			msglen = int(_v)
			if err != nil {
				return err
			}
			if msglen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ticket == nil {
				m.Ticket = &COffline_OfflineLogonTicket{}
			}
			if err := m.Ticket.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
