// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_parental_objects.proto

package unified

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParentalApp struct {
	Appid                *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	IsAllowed            *bool    `protobuf:"varint,2,opt,name=is_allowed,json=isAllowed" json:"is_allowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentalApp) Reset()         { *m = ParentalApp{} }
func (m *ParentalApp) String() string { return proto.CompactTextString(m) }
func (*ParentalApp) ProtoMessage()    {}
func (*ParentalApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b8746b7381fb9e, []int{0}
}

func (m *ParentalApp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalApp.Unmarshal(m, b)
}
func (m *ParentalApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalApp.Marshal(b, m, deterministic)
}
func (m *ParentalApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalApp.Merge(m, src)
}
func (m *ParentalApp) XXX_Size() int {
	return xxx_messageInfo_ParentalApp.Size(m)
}
func (m *ParentalApp) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalApp.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalApp proto.InternalMessageInfo

func (m *ParentalApp) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *ParentalApp) GetIsAllowed() bool {
	if m != nil && m.IsAllowed != nil {
		return *m.IsAllowed
	}
	return false
}

type ParentalPlaytimeDay struct {
	AllowedTimeWindows   *uint64  `protobuf:"varint,1,opt,name=allowed_time_windows,json=allowedTimeWindows" json:"allowed_time_windows,omitempty"`
	AllowedDailyMinutes  *uint32  `protobuf:"varint,2,opt,name=allowed_daily_minutes,json=allowedDailyMinutes" json:"allowed_daily_minutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentalPlaytimeDay) Reset()         { *m = ParentalPlaytimeDay{} }
func (m *ParentalPlaytimeDay) String() string { return proto.CompactTextString(m) }
func (*ParentalPlaytimeDay) ProtoMessage()    {}
func (*ParentalPlaytimeDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b8746b7381fb9e, []int{1}
}

func (m *ParentalPlaytimeDay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalPlaytimeDay.Unmarshal(m, b)
}
func (m *ParentalPlaytimeDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalPlaytimeDay.Marshal(b, m, deterministic)
}
func (m *ParentalPlaytimeDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalPlaytimeDay.Merge(m, src)
}
func (m *ParentalPlaytimeDay) XXX_Size() int {
	return xxx_messageInfo_ParentalPlaytimeDay.Size(m)
}
func (m *ParentalPlaytimeDay) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalPlaytimeDay.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalPlaytimeDay proto.InternalMessageInfo

func (m *ParentalPlaytimeDay) GetAllowedTimeWindows() uint64 {
	if m != nil && m.AllowedTimeWindows != nil {
		return *m.AllowedTimeWindows
	}
	return 0
}

func (m *ParentalPlaytimeDay) GetAllowedDailyMinutes() uint32 {
	if m != nil && m.AllowedDailyMinutes != nil {
		return *m.AllowedDailyMinutes
	}
	return 0
}

type ParentalPlaytimeRestrictions struct {
	ApplyPlaytimeRestrictions *bool                  `protobuf:"varint,2,opt,name=apply_playtime_restrictions,json=applyPlaytimeRestrictions" json:"apply_playtime_restrictions,omitempty"`
	PlaytimeDays              []*ParentalPlaytimeDay `protobuf:"bytes,15,rep,name=playtime_days,json=playtimeDays" json:"playtime_days,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}               `json:"-"`
	XXX_unrecognized          []byte                 `json:"-"`
	XXX_sizecache             int32                  `json:"-"`
}

func (m *ParentalPlaytimeRestrictions) Reset()         { *m = ParentalPlaytimeRestrictions{} }
func (m *ParentalPlaytimeRestrictions) String() string { return proto.CompactTextString(m) }
func (*ParentalPlaytimeRestrictions) ProtoMessage()    {}
func (*ParentalPlaytimeRestrictions) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b8746b7381fb9e, []int{2}
}

func (m *ParentalPlaytimeRestrictions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalPlaytimeRestrictions.Unmarshal(m, b)
}
func (m *ParentalPlaytimeRestrictions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalPlaytimeRestrictions.Marshal(b, m, deterministic)
}
func (m *ParentalPlaytimeRestrictions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalPlaytimeRestrictions.Merge(m, src)
}
func (m *ParentalPlaytimeRestrictions) XXX_Size() int {
	return xxx_messageInfo_ParentalPlaytimeRestrictions.Size(m)
}
func (m *ParentalPlaytimeRestrictions) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalPlaytimeRestrictions.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalPlaytimeRestrictions proto.InternalMessageInfo

func (m *ParentalPlaytimeRestrictions) GetApplyPlaytimeRestrictions() bool {
	if m != nil && m.ApplyPlaytimeRestrictions != nil {
		return *m.ApplyPlaytimeRestrictions
	}
	return false
}

func (m *ParentalPlaytimeRestrictions) GetPlaytimeDays() []*ParentalPlaytimeDay {
	if m != nil {
		return m.PlaytimeDays
	}
	return nil
}

type ParentalTemporaryPlaytimeRestrictions struct {
	Restrictions         *ParentalPlaytimeDay `protobuf:"bytes,1,opt,name=restrictions" json:"restrictions,omitempty"`
	RtimeExpires         *uint32              `protobuf:"varint,2,opt,name=rtime_expires,json=rtimeExpires" json:"rtime_expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ParentalTemporaryPlaytimeRestrictions) Reset()         { *m = ParentalTemporaryPlaytimeRestrictions{} }
func (m *ParentalTemporaryPlaytimeRestrictions) String() string { return proto.CompactTextString(m) }
func (*ParentalTemporaryPlaytimeRestrictions) ProtoMessage()    {}
func (*ParentalTemporaryPlaytimeRestrictions) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b8746b7381fb9e, []int{3}
}

func (m *ParentalTemporaryPlaytimeRestrictions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalTemporaryPlaytimeRestrictions.Unmarshal(m, b)
}
func (m *ParentalTemporaryPlaytimeRestrictions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalTemporaryPlaytimeRestrictions.Marshal(b, m, deterministic)
}
func (m *ParentalTemporaryPlaytimeRestrictions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalTemporaryPlaytimeRestrictions.Merge(m, src)
}
func (m *ParentalTemporaryPlaytimeRestrictions) XXX_Size() int {
	return xxx_messageInfo_ParentalTemporaryPlaytimeRestrictions.Size(m)
}
func (m *ParentalTemporaryPlaytimeRestrictions) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalTemporaryPlaytimeRestrictions.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalTemporaryPlaytimeRestrictions proto.InternalMessageInfo

func (m *ParentalTemporaryPlaytimeRestrictions) GetRestrictions() *ParentalPlaytimeDay {
	if m != nil {
		return m.Restrictions
	}
	return nil
}

func (m *ParentalTemporaryPlaytimeRestrictions) GetRtimeExpires() uint32 {
	if m != nil && m.RtimeExpires != nil {
		return *m.RtimeExpires
	}
	return 0
}

type ParentalSettings struct {
	Steamid                             *uint64                                `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ApplistBaseId                       *uint32                                `protobuf:"varint,2,opt,name=applist_base_id,json=applistBaseId" json:"applist_base_id,omitempty"`
	ApplistBaseDescription              *string                                `protobuf:"bytes,3,opt,name=applist_base_description,json=applistBaseDescription" json:"applist_base_description,omitempty"`
	ApplistBase                         []*ParentalApp                         `protobuf:"bytes,4,rep,name=applist_base,json=applistBase" json:"applist_base,omitempty"`
	ApplistCustom                       []*ParentalApp                         `protobuf:"bytes,5,rep,name=applist_custom,json=applistCustom" json:"applist_custom,omitempty"`
	Passwordhashtype                    *uint32                                `protobuf:"varint,6,opt,name=passwordhashtype" json:"passwordhashtype,omitempty"`
	Salt                                []byte                                 `protobuf:"bytes,7,opt,name=salt" json:"salt,omitempty"`
	Passwordhash                        []byte                                 `protobuf:"bytes,8,opt,name=passwordhash" json:"passwordhash,omitempty"`
	IsEnabled                           *bool                                  `protobuf:"varint,9,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	EnabledFeatures                     *uint32                                `protobuf:"varint,10,opt,name=enabled_features,json=enabledFeatures" json:"enabled_features,omitempty"`
	RecoveryEmail                       *string                                `protobuf:"bytes,11,opt,name=recovery_email,json=recoveryEmail" json:"recovery_email,omitempty"`
	IsSiteLicenseLock                   *bool                                  `protobuf:"varint,12,opt,name=is_site_license_lock,json=isSiteLicenseLock" json:"is_site_license_lock,omitempty"`
	TemporaryEnabledFeatures            *uint32                                `protobuf:"varint,13,opt,name=temporary_enabled_features,json=temporaryEnabledFeatures" json:"temporary_enabled_features,omitempty"`
	RtimeTemporaryFeatureExpiration     *uint32                                `protobuf:"varint,14,opt,name=rtime_temporary_feature_expiration,json=rtimeTemporaryFeatureExpiration" json:"rtime_temporary_feature_expiration,omitempty"`
	PlaytimeRestrictions                *ParentalPlaytimeRestrictions          `protobuf:"bytes,15,opt,name=playtime_restrictions,json=playtimeRestrictions" json:"playtime_restrictions,omitempty"`
	TemporaryPlaytimeRestrictions       *ParentalTemporaryPlaytimeRestrictions `protobuf:"bytes,16,opt,name=temporary_playtime_restrictions,json=temporaryPlaytimeRestrictions" json:"temporary_playtime_restrictions,omitempty"`
	ExcludedStoreContentDescriptors     []uint32                               `protobuf:"varint,17,rep,name=excluded_store_content_descriptors,json=excludedStoreContentDescriptors" json:"excluded_store_content_descriptors,omitempty"`
	ExcludedCommunityContentDescriptors []uint32                               `protobuf:"varint,18,rep,name=excluded_community_content_descriptors,json=excludedCommunityContentDescriptors" json:"excluded_community_content_descriptors,omitempty"`
	UtilityAppids                       []uint32                               `protobuf:"varint,19,rep,name=utility_appids,json=utilityAppids" json:"utility_appids,omitempty"`
	XXX_NoUnkeyedLiteral                struct{}                               `json:"-"`
	XXX_unrecognized                    []byte                                 `json:"-"`
	XXX_sizecache                       int32                                  `json:"-"`
}

func (m *ParentalSettings) Reset()         { *m = ParentalSettings{} }
func (m *ParentalSettings) String() string { return proto.CompactTextString(m) }
func (*ParentalSettings) ProtoMessage()    {}
func (*ParentalSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b8746b7381fb9e, []int{4}
}

func (m *ParentalSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalSettings.Unmarshal(m, b)
}
func (m *ParentalSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalSettings.Marshal(b, m, deterministic)
}
func (m *ParentalSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalSettings.Merge(m, src)
}
func (m *ParentalSettings) XXX_Size() int {
	return xxx_messageInfo_ParentalSettings.Size(m)
}
func (m *ParentalSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalSettings.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalSettings proto.InternalMessageInfo

func (m *ParentalSettings) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *ParentalSettings) GetApplistBaseId() uint32 {
	if m != nil && m.ApplistBaseId != nil {
		return *m.ApplistBaseId
	}
	return 0
}

func (m *ParentalSettings) GetApplistBaseDescription() string {
	if m != nil && m.ApplistBaseDescription != nil {
		return *m.ApplistBaseDescription
	}
	return ""
}

func (m *ParentalSettings) GetApplistBase() []*ParentalApp {
	if m != nil {
		return m.ApplistBase
	}
	return nil
}

func (m *ParentalSettings) GetApplistCustom() []*ParentalApp {
	if m != nil {
		return m.ApplistCustom
	}
	return nil
}

func (m *ParentalSettings) GetPasswordhashtype() uint32 {
	if m != nil && m.Passwordhashtype != nil {
		return *m.Passwordhashtype
	}
	return 0
}

func (m *ParentalSettings) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *ParentalSettings) GetPasswordhash() []byte {
	if m != nil {
		return m.Passwordhash
	}
	return nil
}

func (m *ParentalSettings) GetIsEnabled() bool {
	if m != nil && m.IsEnabled != nil {
		return *m.IsEnabled
	}
	return false
}

func (m *ParentalSettings) GetEnabledFeatures() uint32 {
	if m != nil && m.EnabledFeatures != nil {
		return *m.EnabledFeatures
	}
	return 0
}

func (m *ParentalSettings) GetRecoveryEmail() string {
	if m != nil && m.RecoveryEmail != nil {
		return *m.RecoveryEmail
	}
	return ""
}

func (m *ParentalSettings) GetIsSiteLicenseLock() bool {
	if m != nil && m.IsSiteLicenseLock != nil {
		return *m.IsSiteLicenseLock
	}
	return false
}

func (m *ParentalSettings) GetTemporaryEnabledFeatures() uint32 {
	if m != nil && m.TemporaryEnabledFeatures != nil {
		return *m.TemporaryEnabledFeatures
	}
	return 0
}

func (m *ParentalSettings) GetRtimeTemporaryFeatureExpiration() uint32 {
	if m != nil && m.RtimeTemporaryFeatureExpiration != nil {
		return *m.RtimeTemporaryFeatureExpiration
	}
	return 0
}

func (m *ParentalSettings) GetPlaytimeRestrictions() *ParentalPlaytimeRestrictions {
	if m != nil {
		return m.PlaytimeRestrictions
	}
	return nil
}

func (m *ParentalSettings) GetTemporaryPlaytimeRestrictions() *ParentalTemporaryPlaytimeRestrictions {
	if m != nil {
		return m.TemporaryPlaytimeRestrictions
	}
	return nil
}

func (m *ParentalSettings) GetExcludedStoreContentDescriptors() []uint32 {
	if m != nil {
		return m.ExcludedStoreContentDescriptors
	}
	return nil
}

func (m *ParentalSettings) GetExcludedCommunityContentDescriptors() []uint32 {
	if m != nil {
		return m.ExcludedCommunityContentDescriptors
	}
	return nil
}

func (m *ParentalSettings) GetUtilityAppids() []uint32 {
	if m != nil {
		return m.UtilityAppids
	}
	return nil
}

type ParentalFeatureRequest struct {
	Requestid            *uint64  `protobuf:"fixed64,1,opt,name=requestid" json:"requestid,omitempty"`
	FamilyGroupid        *uint64  `protobuf:"fixed64,2,opt,name=family_groupid,json=familyGroupid" json:"family_groupid,omitempty"`
	Steamid              *uint64  `protobuf:"fixed64,3,opt,name=steamid" json:"steamid,omitempty"`
	Features             *uint32  `protobuf:"varint,4,opt,name=features" json:"features,omitempty"`
	TimeRequested        *uint32  `protobuf:"varint,5,opt,name=time_requested,json=timeRequested" json:"time_requested,omitempty"`
	Approved             *bool    `protobuf:"varint,6,opt,name=approved" json:"approved,omitempty"`
	SteamidResponder     *uint64  `protobuf:"fixed64,7,opt,name=steamid_responder,json=steamidResponder" json:"steamid_responder,omitempty"`
	TimeResponded        *uint32  `protobuf:"varint,8,opt,name=time_responded,json=timeResponded" json:"time_responded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentalFeatureRequest) Reset()         { *m = ParentalFeatureRequest{} }
func (m *ParentalFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*ParentalFeatureRequest) ProtoMessage()    {}
func (*ParentalFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b8746b7381fb9e, []int{5}
}

func (m *ParentalFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalFeatureRequest.Unmarshal(m, b)
}
func (m *ParentalFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalFeatureRequest.Marshal(b, m, deterministic)
}
func (m *ParentalFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalFeatureRequest.Merge(m, src)
}
func (m *ParentalFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_ParentalFeatureRequest.Size(m)
}
func (m *ParentalFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalFeatureRequest proto.InternalMessageInfo

func (m *ParentalFeatureRequest) GetRequestid() uint64 {
	if m != nil && m.Requestid != nil {
		return *m.Requestid
	}
	return 0
}

func (m *ParentalFeatureRequest) GetFamilyGroupid() uint64 {
	if m != nil && m.FamilyGroupid != nil {
		return *m.FamilyGroupid
	}
	return 0
}

func (m *ParentalFeatureRequest) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *ParentalFeatureRequest) GetFeatures() uint32 {
	if m != nil && m.Features != nil {
		return *m.Features
	}
	return 0
}

func (m *ParentalFeatureRequest) GetTimeRequested() uint32 {
	if m != nil && m.TimeRequested != nil {
		return *m.TimeRequested
	}
	return 0
}

func (m *ParentalFeatureRequest) GetApproved() bool {
	if m != nil && m.Approved != nil {
		return *m.Approved
	}
	return false
}

func (m *ParentalFeatureRequest) GetSteamidResponder() uint64 {
	if m != nil && m.SteamidResponder != nil {
		return *m.SteamidResponder
	}
	return 0
}

func (m *ParentalFeatureRequest) GetTimeResponded() uint32 {
	if m != nil && m.TimeResponded != nil {
		return *m.TimeResponded
	}
	return 0
}

type ParentalPlaytimeRequest struct {
	Requestid                   *uint64                                `protobuf:"fixed64,1,opt,name=requestid" json:"requestid,omitempty"`
	FamilyGroupid               *uint64                                `protobuf:"fixed64,2,opt,name=family_groupid,json=familyGroupid" json:"family_groupid,omitempty"`
	Steamid                     *uint64                                `protobuf:"fixed64,3,opt,name=steamid" json:"steamid,omitempty"`
	CurrentPlaytimeRestrictions *ParentalPlaytimeDay                   `protobuf:"bytes,4,opt,name=current_playtime_restrictions,json=currentPlaytimeRestrictions" json:"current_playtime_restrictions,omitempty"`
	TimeExpires                 *uint32                                `protobuf:"varint,5,opt,name=time_expires,json=timeExpires" json:"time_expires,omitempty"`
	TimeRequested               *uint32                                `protobuf:"varint,6,opt,name=time_requested,json=timeRequested" json:"time_requested,omitempty"`
	Approved                    *bool                                  `protobuf:"varint,7,opt,name=approved" json:"approved,omitempty"`
	SteamidResponder            *uint64                                `protobuf:"fixed64,8,opt,name=steamid_responder,json=steamidResponder" json:"steamid_responder,omitempty"`
	TimeResponded               *uint32                                `protobuf:"varint,9,opt,name=time_responded,json=timeResponded" json:"time_responded,omitempty"`
	RestrictionsApproved        *ParentalTemporaryPlaytimeRestrictions `protobuf:"bytes,10,opt,name=restrictions_approved,json=restrictionsApproved" json:"restrictions_approved,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                               `json:"-"`
	XXX_unrecognized            []byte                                 `json:"-"`
	XXX_sizecache               int32                                  `json:"-"`
}

func (m *ParentalPlaytimeRequest) Reset()         { *m = ParentalPlaytimeRequest{} }
func (m *ParentalPlaytimeRequest) String() string { return proto.CompactTextString(m) }
func (*ParentalPlaytimeRequest) ProtoMessage()    {}
func (*ParentalPlaytimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b8746b7381fb9e, []int{6}
}

func (m *ParentalPlaytimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentalPlaytimeRequest.Unmarshal(m, b)
}
func (m *ParentalPlaytimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentalPlaytimeRequest.Marshal(b, m, deterministic)
}
func (m *ParentalPlaytimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentalPlaytimeRequest.Merge(m, src)
}
func (m *ParentalPlaytimeRequest) XXX_Size() int {
	return xxx_messageInfo_ParentalPlaytimeRequest.Size(m)
}
func (m *ParentalPlaytimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentalPlaytimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParentalPlaytimeRequest proto.InternalMessageInfo

func (m *ParentalPlaytimeRequest) GetRequestid() uint64 {
	if m != nil && m.Requestid != nil {
		return *m.Requestid
	}
	return 0
}

func (m *ParentalPlaytimeRequest) GetFamilyGroupid() uint64 {
	if m != nil && m.FamilyGroupid != nil {
		return *m.FamilyGroupid
	}
	return 0
}

func (m *ParentalPlaytimeRequest) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *ParentalPlaytimeRequest) GetCurrentPlaytimeRestrictions() *ParentalPlaytimeDay {
	if m != nil {
		return m.CurrentPlaytimeRestrictions
	}
	return nil
}

func (m *ParentalPlaytimeRequest) GetTimeExpires() uint32 {
	if m != nil && m.TimeExpires != nil {
		return *m.TimeExpires
	}
	return 0
}

func (m *ParentalPlaytimeRequest) GetTimeRequested() uint32 {
	if m != nil && m.TimeRequested != nil {
		return *m.TimeRequested
	}
	return 0
}

func (m *ParentalPlaytimeRequest) GetApproved() bool {
	if m != nil && m.Approved != nil {
		return *m.Approved
	}
	return false
}

func (m *ParentalPlaytimeRequest) GetSteamidResponder() uint64 {
	if m != nil && m.SteamidResponder != nil {
		return *m.SteamidResponder
	}
	return 0
}

func (m *ParentalPlaytimeRequest) GetTimeResponded() uint32 {
	if m != nil && m.TimeResponded != nil {
		return *m.TimeResponded
	}
	return 0
}

func (m *ParentalPlaytimeRequest) GetRestrictionsApproved() *ParentalTemporaryPlaytimeRestrictions {
	if m != nil {
		return m.RestrictionsApproved
	}
	return nil
}

func init() {
	proto.RegisterType((*ParentalApp)(nil), "ParentalApp")
	proto.RegisterType((*ParentalPlaytimeDay)(nil), "ParentalPlaytimeDay")
	proto.RegisterType((*ParentalPlaytimeRestrictions)(nil), "ParentalPlaytimeRestrictions")
	proto.RegisterType((*ParentalTemporaryPlaytimeRestrictions)(nil), "ParentalTemporaryPlaytimeRestrictions")
	proto.RegisterType((*ParentalSettings)(nil), "ParentalSettings")
	proto.RegisterType((*ParentalFeatureRequest)(nil), "ParentalFeatureRequest")
	proto.RegisterType((*ParentalPlaytimeRequest)(nil), "ParentalPlaytimeRequest")
}

func init() {
	proto.RegisterFile("steammessages_parental_objects.proto", fileDescriptor_46b8746b7381fb9e)
}

var fileDescriptor_46b8746b7381fb9e = []byte{
	// 916 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x86, 0x6b, 0xc7, 0xb1, 0x8f, 0xed, 0xc4, 0x61, 0x9c, 0x4e, 0x4b, 0x1b, 0xd4, 0x53, 0x97,
	0xc0, 0xdb, 0x00, 0x77, 0xe8, 0x6e, 0x3a, 0x60, 0x18, 0x90, 0x1f, 0xef, 0x07, 0xed, 0x80, 0x42,
	0x29, 0xb0, 0x01, 0xbb, 0x20, 0x18, 0xe9, 0x34, 0xe5, 0x2a, 0x89, 0x1c, 0x49, 0x35, 0x35, 0x76,
	0xbf, 0x07, 0xd8, 0xdd, 0x5e, 0x61, 0x6f, 0xb6, 0xb7, 0x18, 0x44, 0x51, 0xb2, 0xdc, 0xa8, 0x59,
	0x76, 0xb3, 0x3b, 0xf1, 0x3b, 0xdf, 0xf9, 0xce, 0xd1, 0xf9, 0x21, 0xe1, 0x63, 0x6d, 0x90, 0x25,
	0x09, 0x6a, 0xcd, 0x2e, 0x51, 0x53, 0xc9, 0x14, 0xa6, 0x86, 0xc5, 0x54, 0x5c, 0xfc, 0x82, 0xa1,
	0xd1, 0x73, 0xa9, 0x84, 0x11, 0xfb, 0x03, 0x4c, 0xb3, 0xc4, 0x1d, 0xfc, 0x13, 0x18, 0x3c, 0x77,
	0xb4, 0x63, 0x29, 0xc9, 0x04, 0x36, 0x98, 0x94, 0x3c, 0xf2, 0x5a, 0xd3, 0xd6, 0x6c, 0x14, 0x14,
	0x07, 0x72, 0x00, 0xc0, 0x35, 0x65, 0x71, 0x2c, 0xae, 0x30, 0xf2, 0xee, 0x4c, 0x5b, 0xb3, 0x5e,
	0xd0, 0xe7, 0xfa, 0xb8, 0x00, 0xfc, 0xdf, 0x60, 0xb7, 0xd4, 0x78, 0x1e, 0xb3, 0xa5, 0xe1, 0x09,
	0x9e, 0xb1, 0x25, 0xf9, 0x1c, 0x26, 0xce, 0x85, 0xe6, 0x10, 0xbd, 0xe2, 0x69, 0x24, 0xae, 0xb4,
	0x95, 0xee, 0x04, 0xc4, 0xd9, 0x5e, 0xf0, 0x04, 0x7f, 0x2c, 0x2c, 0xe4, 0x31, 0xec, 0x95, 0x1e,
	0x11, 0xe3, 0xf1, 0x92, 0x26, 0x3c, 0xcd, 0x0c, 0x6a, 0x1b, 0x72, 0x14, 0xec, 0x3a, 0xe3, 0x59,
	0x6e, 0xfb, 0xa1, 0x30, 0xf9, 0x7f, 0xb6, 0xe0, 0xfe, 0xbb, 0xd1, 0x03, 0xd4, 0x46, 0xf1, 0xd0,
	0x70, 0x91, 0x6a, 0xf2, 0x35, 0xdc, 0x63, 0x52, 0xc6, 0x4b, 0x2a, 0x9d, 0x95, 0xaa, 0x9a, 0xd9,
	0xfd, 0xcd, 0x87, 0x96, 0xd2, 0xe8, 0xff, 0x25, 0x8c, 0x2a, 0xcf, 0x88, 0x2d, 0xb5, 0xb7, 0x3d,
	0x6d, 0xcf, 0x06, 0x8f, 0x27, 0xf3, 0x86, 0x7f, 0x0e, 0x86, 0x72, 0x75, 0xd0, 0xfe, 0xef, 0x2d,
	0x38, 0x2c, 0x59, 0x2f, 0x30, 0x91, 0x42, 0x31, 0xd5, 0x1c, 0xe4, 0x09, 0x0c, 0xd7, 0xb2, 0xca,
	0x6b, 0xf4, 0xde, 0x18, 0x75, 0x26, 0x79, 0x08, 0x23, 0x65, 0x73, 0xc3, 0xb7, 0x92, 0xab, 0xaa,
	0x56, 0x43, 0x0b, 0x2e, 0x0a, 0xcc, 0xff, 0xa3, 0x07, 0xe3, 0x52, 0xea, 0x1c, 0x8d, 0xe1, 0xe9,
	0xa5, 0x26, 0x1e, 0x6c, 0xda, 0x79, 0x71, 0xdd, 0xee, 0x06, 0xe5, 0x91, 0x1c, 0xc1, 0x76, 0x5e,
	0x0f, 0xae, 0x0d, 0xbd, 0x60, 0x1a, 0x29, 0x8f, 0x9c, 0xea, 0xc8, 0xc1, 0x27, 0x4c, 0xe3, 0xf7,
	0x11, 0x79, 0x02, 0xde, 0x1a, 0x2f, 0x42, 0x1d, 0x2a, 0x2e, 0xf3, 0xc4, 0xbc, 0xf6, 0xb4, 0x35,
	0xeb, 0x07, 0x77, 0x6b, 0x0e, 0x67, 0x2b, 0x2b, 0x79, 0x04, 0xc3, 0xba, 0xa7, 0xd7, 0xb1, 0x35,
	0x1d, 0xce, 0x6b, 0xb3, 0x18, 0x0c, 0x6a, 0xbe, 0xe4, 0x0b, 0xd8, 0x2a, 0x1d, 0xc2, 0x4c, 0x1b,
	0x91, 0x78, 0x1b, 0x0d, 0x2e, 0x65, 0x7e, 0xa7, 0x96, 0x42, 0x3e, 0x85, 0xb1, 0x64, 0x5a, 0x5f,
	0x09, 0x15, 0xbd, 0x62, 0xfa, 0x95, 0x59, 0x4a, 0xf4, 0xba, 0xf6, 0x47, 0xae, 0xe1, 0x84, 0x40,
	0x47, 0xb3, 0xd8, 0x78, 0x9b, 0xd3, 0xd6, 0x6c, 0x18, 0xd8, 0x6f, 0xe2, 0xc3, 0xb0, 0xce, 0xf3,
	0x7a, 0xd6, 0xb6, 0x86, 0xb9, 0xdd, 0xc0, 0x94, 0x5d, 0xc4, 0x18, 0x79, 0xfd, 0x72, 0x37, 0x16,
	0x05, 0x40, 0x3e, 0x81, 0xb1, 0xb3, 0xd1, 0x97, 0xc8, 0x4c, 0x96, 0x77, 0x08, 0x6c, 0x0a, 0xdb,
	0x0e, 0xff, 0xc6, 0xc1, 0xe4, 0x10, 0xb6, 0x14, 0x86, 0xe2, 0x0d, 0xaa, 0x25, 0xc5, 0x84, 0xf1,
	0xd8, 0x1b, 0xd8, 0x1a, 0x8e, 0x4a, 0x74, 0x91, 0x83, 0xe4, 0x11, 0x4c, 0xb8, 0xa6, 0x9a, 0x1b,
	0xa4, 0x31, 0x0f, 0x31, 0xd5, 0x48, 0x63, 0x11, 0xbe, 0xf6, 0x86, 0x36, 0xf4, 0x0e, 0xd7, 0xe7,
	0xdc, 0xe0, 0xb3, 0xc2, 0xf2, 0x4c, 0x84, 0xaf, 0xc9, 0x57, 0xb0, 0x6f, 0xca, 0xe1, 0xa3, 0xd7,
	0x92, 0x19, 0xd9, 0x64, 0xbc, 0x8a, 0xb1, 0x78, 0x27, 0xab, 0xa7, 0xe0, 0x17, 0xf3, 0xb5, 0xd2,
	0x70, 0xbe, 0xc5, 0xc4, 0x31, 0xdb, 0xed, 0x2d, 0xab, 0xf2, 0xc0, 0x32, 0xab, 0x49, 0x77, 0x1a,
	0x8b, 0x8a, 0x46, 0x02, 0xd8, 0x6b, 0xde, 0xc2, 0x6d, 0x3b, 0xef, 0x07, 0xf3, 0x9b, 0x36, 0x39,
	0x98, 0xc8, 0xa6, 0xd5, 0x49, 0xe1, 0xc1, 0x2a, 0xb5, 0x66, 0xf5, 0xb1, 0x55, 0x3f, 0x9a, 0xdf,
	0x6a, 0x17, 0x83, 0x03, 0x73, 0xe3, 0xaa, 0x3e, 0x05, 0x1f, 0xdf, 0x86, 0x71, 0x16, 0x61, 0x44,
	0xb5, 0x11, 0x0a, 0x69, 0x28, 0x52, 0x83, 0xa9, 0xa9, 0xc6, 0x5f, 0x28, 0xed, 0xed, 0x4c, 0xdb,
	0x79, 0x41, 0x4a, 0xe6, 0x79, 0x4e, 0x3c, 0x2d, 0x78, 0x67, 0x2b, 0x1a, 0x39, 0x87, 0xa3, 0x4a,
	0x2c, 0x14, 0x49, 0x92, 0xa5, 0xdc, 0x2c, 0x1b, 0x05, 0x89, 0x15, 0x7c, 0x58, 0xb2, 0x4f, 0x4b,
	0x72, 0x83, 0xe8, 0x21, 0x6c, 0x65, 0x86, 0xc7, 0xb9, 0x92, 0xbd, 0xbf, 0xb5, 0xb7, 0x6b, 0x9d,
	0x47, 0x0e, 0x3d, 0xb6, 0xa0, 0xff, 0xd7, 0x1d, 0xb8, 0x5b, 0x56, 0xc4, 0xb5, 0x2a, 0xc0, 0x5f,
	0x33, 0xd4, 0x86, 0xdc, 0x87, 0xbe, 0x2a, 0x3e, 0xab, 0xcb, 0x61, 0x05, 0xe4, 0xfa, 0x2f, 0x59,
	0x92, 0xdf, 0xcf, 0x97, 0x4a, 0x64, 0xd2, 0xdd, 0x0e, 0xdd, 0x60, 0x54, 0xa0, 0xdf, 0x16, 0x60,
	0xfd, 0x7e, 0x69, 0xaf, 0xdf, 0x2f, 0xfb, 0xd0, 0xab, 0xe6, 0xaf, 0x63, 0x27, 0xa7, 0x3a, 0xe7,
	0xe2, 0xae, 0x81, 0x36, 0x1c, 0x46, 0xde, 0x46, 0x71, 0xf5, 0x14, 0x8d, 0x70, 0x60, 0x2e, 0xc1,
	0xa4, 0x54, 0xe2, 0x0d, 0x46, 0x76, 0xa5, 0x7b, 0x41, 0x75, 0x26, 0x9f, 0xc1, 0x8e, 0x8b, 0x94,
	0x8f, 0x81, 0x14, 0x69, 0x84, 0xca, 0xee, 0x75, 0x37, 0x18, 0x3b, 0x43, 0x50, 0xe2, 0xb5, 0x78,
	0x05, 0x12, 0xd9, 0x2d, 0xaf, 0xe2, 0x39, 0xd0, 0xff, 0xbb, 0x0d, 0x1f, 0x5c, 0x1f, 0xce, 0xff,
	0xa5, 0x5a, 0x3f, 0xc1, 0x41, 0x98, 0xa9, 0x3c, 0xf4, 0x7b, 0xc6, 0xbb, 0x73, 0xc3, 0x63, 0x71,
	0xcf, 0xb9, 0x36, 0x8e, 0xf2, 0x47, 0x30, 0x5c, 0x7b, 0x3a, 0x8a, 0x4a, 0x0f, 0x6a, 0x2f, 0x47,
	0x43, 0x3b, 0xba, 0xff, 0xd6, 0x8e, 0xcd, 0xdb, 0xb4, 0xa3, 0x77, 0xeb, 0x76, 0xf4, 0x1b, 0xda,
	0x41, 0x7e, 0x86, 0xbd, 0x7a, 0x09, 0x68, 0x15, 0x1c, 0xfe, 0xd3, 0xaa, 0x4f, 0xea, 0x22, 0xc7,
	0x4e, 0xe3, 0xe4, 0xce, 0x77, 0xad, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x3f, 0xa9, 0x5b,
	0x4b, 0x09, 0x00, 0x00,
}
