// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.18.0
// source: github.com/paralin/go-steam/protocol/protobuf/unified/partnerapps.proto

package unified

import (
	fmt "fmt"
	io "io"
	slices "slices"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	_ "github.com/paralin/go-steam/protocol/protobuf"
)

type CPartnerApps_RequestUploadToken_Request struct {
	unknownFields []byte
	Filename      *string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Appid         *uint32 `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
}

func (x *CPartnerApps_RequestUploadToken_Request) Reset() {
	*x = CPartnerApps_RequestUploadToken_Request{}
}

func (*CPartnerApps_RequestUploadToken_Request) ProtoMessage() {}

func (x *CPartnerApps_RequestUploadToken_Request) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

func (x *CPartnerApps_RequestUploadToken_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

type CPartnerApps_RequestUploadToken_Response struct {
	unknownFields []byte
	UploadToken   *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"uploadToken,omitempty"`
	Location      *string `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	RoutingId     *uint64 `protobuf:"varint,3,opt,name=routing_id,json=routingId" json:"routingId,omitempty"`
}

func (x *CPartnerApps_RequestUploadToken_Response) Reset() {
	*x = CPartnerApps_RequestUploadToken_Response{}
}

func (*CPartnerApps_RequestUploadToken_Response) ProtoMessage() {}

func (x *CPartnerApps_RequestUploadToken_Response) GetUploadToken() uint64 {
	if x != nil && x.UploadToken != nil {
		return *x.UploadToken
	}
	return 0
}

func (x *CPartnerApps_RequestUploadToken_Response) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *CPartnerApps_RequestUploadToken_Response) GetRoutingId() uint64 {
	if x != nil && x.RoutingId != nil {
		return *x.RoutingId
	}
	return 0
}

type CPartnerApps_FinishUpload_Request struct {
	unknownFields []byte
	UploadToken   *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"uploadToken,omitempty"`
	RoutingId     *uint64 `protobuf:"varint,2,opt,name=routing_id,json=routingId" json:"routingId,omitempty"`
	AppId         *uint32 `protobuf:"varint,3,opt,name=app_id,json=appId" json:"appId,omitempty"`
}

func (x *CPartnerApps_FinishUpload_Request) Reset() {
	*x = CPartnerApps_FinishUpload_Request{}
}

func (*CPartnerApps_FinishUpload_Request) ProtoMessage() {}

func (x *CPartnerApps_FinishUpload_Request) GetUploadToken() uint64 {
	if x != nil && x.UploadToken != nil {
		return *x.UploadToken
	}
	return 0
}

func (x *CPartnerApps_FinishUpload_Request) GetRoutingId() uint64 {
	if x != nil && x.RoutingId != nil {
		return *x.RoutingId
	}
	return 0
}

func (x *CPartnerApps_FinishUpload_Request) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

type CPartnerApps_FinishUploadKVSign_Response struct {
	unknownFields       []byte
	SignedInstallscript *string `protobuf:"bytes,1,opt,name=signed_installscript,json=signedInstallscript" json:"signedInstallscript,omitempty"`
}

func (x *CPartnerApps_FinishUploadKVSign_Response) Reset() {
	*x = CPartnerApps_FinishUploadKVSign_Response{}
}

func (*CPartnerApps_FinishUploadKVSign_Response) ProtoMessage() {}

func (x *CPartnerApps_FinishUploadKVSign_Response) GetSignedInstallscript() string {
	if x != nil && x.SignedInstallscript != nil {
		return *x.SignedInstallscript
	}
	return ""
}

type CPartnerApps_FinishUploadLegacyDRM_Request struct {
	unknownFields []byte
	UploadToken   *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"uploadToken,omitempty"`
	RoutingId     *uint64 `protobuf:"varint,2,opt,name=routing_id,json=routingId" json:"routingId,omitempty"`
	AppId         *uint32 `protobuf:"varint,3,opt,name=app_id,json=appId" json:"appId,omitempty"`
	Flags         *uint32 `protobuf:"varint,4,opt,name=flags" json:"flags,omitempty"`
	ToolName      *string `protobuf:"bytes,5,opt,name=tool_name,json=toolName" json:"toolName,omitempty"`
	UseCloud      *bool   `protobuf:"varint,6,opt,name=use_cloud,json=useCloud,def=0" json:"useCloud,omitempty"`
}

// Default values for CPartnerApps_FinishUploadLegacyDRM_Request fields.
const (
	Default_CPartnerApps_FinishUploadLegacyDRM_Request_UseCloud = bool(false)
)

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) Reset() {
	*x = CPartnerApps_FinishUploadLegacyDRM_Request{}
}

func (*CPartnerApps_FinishUploadLegacyDRM_Request) ProtoMessage() {}

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) GetUploadToken() uint64 {
	if x != nil && x.UploadToken != nil {
		return *x.UploadToken
	}
	return 0
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) GetRoutingId() uint64 {
	if x != nil && x.RoutingId != nil {
		return *x.RoutingId
	}
	return 0
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) GetUseCloud() bool {
	if x != nil && x.UseCloud != nil {
		return *x.UseCloud
	}
	return Default_CPartnerApps_FinishUploadLegacyDRM_Request_UseCloud
}

type CPartnerApps_FinishUploadLegacyDRM_Response struct {
	unknownFields []byte
	FileId        *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"fileId,omitempty"`
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Response) Reset() {
	*x = CPartnerApps_FinishUploadLegacyDRM_Response{}
}

func (*CPartnerApps_FinishUploadLegacyDRM_Response) ProtoMessage() {}

func (x *CPartnerApps_FinishUploadLegacyDRM_Response) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

type CPartnerApps_FinishUpload_Response struct {
	unknownFields []byte
}

func (x *CPartnerApps_FinishUpload_Response) Reset() {
	*x = CPartnerApps_FinishUpload_Response{}
}

func (*CPartnerApps_FinishUpload_Response) ProtoMessage() {}

type CPartnerApps_FinishUploadDepot_Request struct {
	unknownFields []byte
	UploadToken   *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"uploadToken,omitempty"`
	RoutingId     *uint64 `protobuf:"varint,2,opt,name=routing_id,json=routingId" json:"routingId,omitempty"`
	AppId         *uint32 `protobuf:"varint,3,opt,name=app_id,json=appId" json:"appId,omitempty"`
	DepotId       *uint32 `protobuf:"varint,4,opt,name=depot_id,json=depotId" json:"depotId,omitempty"`
	BuildFlags    *uint32 `protobuf:"varint,5,opt,name=build_flags,json=buildFlags" json:"buildFlags,omitempty"`
}

func (x *CPartnerApps_FinishUploadDepot_Request) Reset() {
	*x = CPartnerApps_FinishUploadDepot_Request{}
}

func (*CPartnerApps_FinishUploadDepot_Request) ProtoMessage() {}

func (x *CPartnerApps_FinishUploadDepot_Request) GetUploadToken() uint64 {
	if x != nil && x.UploadToken != nil {
		return *x.UploadToken
	}
	return 0
}

func (x *CPartnerApps_FinishUploadDepot_Request) GetRoutingId() uint64 {
	if x != nil && x.RoutingId != nil {
		return *x.RoutingId
	}
	return 0
}

func (x *CPartnerApps_FinishUploadDepot_Request) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CPartnerApps_FinishUploadDepot_Request) GetDepotId() uint32 {
	if x != nil && x.DepotId != nil {
		return *x.DepotId
	}
	return 0
}

func (x *CPartnerApps_FinishUploadDepot_Request) GetBuildFlags() uint32 {
	if x != nil && x.BuildFlags != nil {
		return *x.BuildFlags
	}
	return 0
}

type CPartnerApps_FinishUploadDepot_Response struct {
	unknownFields  []byte
	BuildRoutingId *uint64 `protobuf:"varint,1,opt,name=build_routing_id,json=buildRoutingId" json:"buildRoutingId,omitempty"`
}

func (x *CPartnerApps_FinishUploadDepot_Response) Reset() {
	*x = CPartnerApps_FinishUploadDepot_Response{}
}

func (*CPartnerApps_FinishUploadDepot_Response) ProtoMessage() {}

func (x *CPartnerApps_FinishUploadDepot_Response) GetBuildRoutingId() uint64 {
	if x != nil && x.BuildRoutingId != nil {
		return *x.BuildRoutingId
	}
	return 0
}

type CPartnerApps_GetDepotBuildResult_Request struct {
	unknownFields []byte
	UploadToken   *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"uploadToken,omitempty"`
	RoutingId     *uint64 `protobuf:"varint,2,opt,name=routing_id,json=routingId" json:"routingId,omitempty"`
}

func (x *CPartnerApps_GetDepotBuildResult_Request) Reset() {
	*x = CPartnerApps_GetDepotBuildResult_Request{}
}

func (*CPartnerApps_GetDepotBuildResult_Request) ProtoMessage() {}

func (x *CPartnerApps_GetDepotBuildResult_Request) GetUploadToken() uint64 {
	if x != nil && x.UploadToken != nil {
		return *x.UploadToken
	}
	return 0
}

func (x *CPartnerApps_GetDepotBuildResult_Request) GetRoutingId() uint64 {
	if x != nil && x.RoutingId != nil {
		return *x.RoutingId
	}
	return 0
}

type CPartnerApps_GetDepotBuildResult_Response struct {
	unknownFields []byte
	ManifestId    *uint64 `protobuf:"varint,1,opt,name=manifest_id,json=manifestId" json:"manifestId,omitempty"`
	ErrorMsg      *string `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg" json:"errorMsg,omitempty"`
}

func (x *CPartnerApps_GetDepotBuildResult_Response) Reset() {
	*x = CPartnerApps_GetDepotBuildResult_Response{}
}

func (*CPartnerApps_GetDepotBuildResult_Response) ProtoMessage() {}

func (x *CPartnerApps_GetDepotBuildResult_Response) GetManifestId() uint64 {
	if x != nil && x.ManifestId != nil {
		return *x.ManifestId
	}
	return 0
}

func (x *CPartnerApps_GetDepotBuildResult_Response) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

type CPartnerApps_FindDRMUploads_Request struct {
	unknownFields []byte
	AppId         *int32 `protobuf:"varint,1,opt,name=app_id,json=appId" json:"appId,omitempty"`
}

func (x *CPartnerApps_FindDRMUploads_Request) Reset() {
	*x = CPartnerApps_FindDRMUploads_Request{}
}

func (*CPartnerApps_FindDRMUploads_Request) ProtoMessage() {}

func (x *CPartnerApps_FindDRMUploads_Request) GetAppId() int32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

type CPartnerApps_ExistingDRMUpload struct {
	unknownFields []byte
	FileId        *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"fileId,omitempty"`
	AppId         *uint32 `protobuf:"varint,2,opt,name=app_id,json=appId" json:"appId,omitempty"`
	ActorId       *int32  `protobuf:"varint,3,opt,name=actor_id,json=actorId" json:"actorId,omitempty"`
	SuppliedName  *string `protobuf:"bytes,5,opt,name=supplied_name,json=suppliedName" json:"suppliedName,omitempty"`
	Flags         *uint32 `protobuf:"varint,6,opt,name=flags" json:"flags,omitempty"`
	ModType       *string `protobuf:"bytes,7,opt,name=mod_type,json=modType" json:"modType,omitempty"`
	Timestamp     *uint32 `protobuf:"fixed32,8,opt,name=timestamp" json:"timestamp,omitempty"`
	OrigFileId    *string `protobuf:"bytes,9,opt,name=orig_file_id,json=origFileId" json:"origFileId,omitempty"`
}

func (x *CPartnerApps_ExistingDRMUpload) Reset() {
	*x = CPartnerApps_ExistingDRMUpload{}
}

func (*CPartnerApps_ExistingDRMUpload) ProtoMessage() {}

func (x *CPartnerApps_ExistingDRMUpload) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *CPartnerApps_ExistingDRMUpload) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CPartnerApps_ExistingDRMUpload) GetActorId() int32 {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return 0
}

func (x *CPartnerApps_ExistingDRMUpload) GetSuppliedName() string {
	if x != nil && x.SuppliedName != nil {
		return *x.SuppliedName
	}
	return ""
}

func (x *CPartnerApps_ExistingDRMUpload) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *CPartnerApps_ExistingDRMUpload) GetModType() string {
	if x != nil && x.ModType != nil {
		return *x.ModType
	}
	return ""
}

func (x *CPartnerApps_ExistingDRMUpload) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *CPartnerApps_ExistingDRMUpload) GetOrigFileId() string {
	if x != nil && x.OrigFileId != nil {
		return *x.OrigFileId
	}
	return ""
}

type CPartnerApps_FindDRMUploads_Response struct {
	unknownFields []byte
	Uploads       []*CPartnerApps_ExistingDRMUpload `protobuf:"bytes,1,rep,name=uploads" json:"uploads,omitempty"`
}

func (x *CPartnerApps_FindDRMUploads_Response) Reset() {
	*x = CPartnerApps_FindDRMUploads_Response{}
}

func (*CPartnerApps_FindDRMUploads_Response) ProtoMessage() {}

func (x *CPartnerApps_FindDRMUploads_Response) GetUploads() []*CPartnerApps_ExistingDRMUpload {
	if x != nil {
		return x.Uploads
	}
	return nil
}

type CPartnerApps_Download_Request struct {
	unknownFields []byte
	FileId        *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"fileId,omitempty"`
	AppId         *int32  `protobuf:"varint,2,opt,name=app_id,json=appId" json:"appId,omitempty"`
}

func (x *CPartnerApps_Download_Request) Reset() {
	*x = CPartnerApps_Download_Request{}
}

func (*CPartnerApps_Download_Request) ProtoMessage() {}

func (x *CPartnerApps_Download_Request) GetFileId() string {
	if x != nil && x.FileId != nil {
		return *x.FileId
	}
	return ""
}

func (x *CPartnerApps_Download_Request) GetAppId() int32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

type CPartnerApps_Download_Response struct {
	unknownFields []byte
	DownloadUrl   *string `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl" json:"downloadUrl,omitempty"`
	AppId         *int32  `protobuf:"varint,2,opt,name=app_id,json=appId" json:"appId,omitempty"`
}

func (x *CPartnerApps_Download_Response) Reset() {
	*x = CPartnerApps_Download_Response{}
}

func (*CPartnerApps_Download_Response) ProtoMessage() {}

func (x *CPartnerApps_Download_Response) GetDownloadUrl() string {
	if x != nil && x.DownloadUrl != nil {
		return *x.DownloadUrl
	}
	return ""
}

func (x *CPartnerApps_Download_Response) GetAppId() int32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (m *CPartnerApps_RequestUploadToken_Request) CloneVT() *CPartnerApps_RequestUploadToken_Request {
	if m == nil {
		return (*CPartnerApps_RequestUploadToken_Request)(nil)
	}
	r := new(CPartnerApps_RequestUploadToken_Request)
	r.Filename = protobuf_go_lite.ClonePtr(m.Filename)
	r.Appid = protobuf_go_lite.ClonePtr(m.Appid)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_RequestUploadToken_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_RequestUploadToken_Response) CloneVT() *CPartnerApps_RequestUploadToken_Response {
	if m == nil {
		return (*CPartnerApps_RequestUploadToken_Response)(nil)
	}
	r := new(CPartnerApps_RequestUploadToken_Response)
	r.UploadToken = protobuf_go_lite.ClonePtr(m.UploadToken)
	r.Location = protobuf_go_lite.ClonePtr(m.Location)
	r.RoutingId = protobuf_go_lite.ClonePtr(m.RoutingId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_RequestUploadToken_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FinishUpload_Request) CloneVT() *CPartnerApps_FinishUpload_Request {
	if m == nil {
		return (*CPartnerApps_FinishUpload_Request)(nil)
	}
	r := new(CPartnerApps_FinishUpload_Request)
	r.UploadToken = protobuf_go_lite.ClonePtr(m.UploadToken)
	r.RoutingId = protobuf_go_lite.ClonePtr(m.RoutingId)
	r.AppId = protobuf_go_lite.ClonePtr(m.AppId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FinishUpload_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FinishUploadKVSign_Response) CloneVT() *CPartnerApps_FinishUploadKVSign_Response {
	if m == nil {
		return (*CPartnerApps_FinishUploadKVSign_Response)(nil)
	}
	r := new(CPartnerApps_FinishUploadKVSign_Response)
	r.SignedInstallscript = protobuf_go_lite.ClonePtr(m.SignedInstallscript)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FinishUploadKVSign_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) CloneVT() *CPartnerApps_FinishUploadLegacyDRM_Request {
	if m == nil {
		return (*CPartnerApps_FinishUploadLegacyDRM_Request)(nil)
	}
	r := new(CPartnerApps_FinishUploadLegacyDRM_Request)
	r.UploadToken = protobuf_go_lite.ClonePtr(m.UploadToken)
	r.RoutingId = protobuf_go_lite.ClonePtr(m.RoutingId)
	r.AppId = protobuf_go_lite.ClonePtr(m.AppId)
	r.Flags = protobuf_go_lite.ClonePtr(m.Flags)
	r.ToolName = protobuf_go_lite.ClonePtr(m.ToolName)
	r.UseCloud = protobuf_go_lite.ClonePtr(m.UseCloud)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) CloneVT() *CPartnerApps_FinishUploadLegacyDRM_Response {
	if m == nil {
		return (*CPartnerApps_FinishUploadLegacyDRM_Response)(nil)
	}
	r := new(CPartnerApps_FinishUploadLegacyDRM_Response)
	r.FileId = protobuf_go_lite.ClonePtr(m.FileId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FinishUpload_Response) CloneVT() *CPartnerApps_FinishUpload_Response {
	if m == nil {
		return (*CPartnerApps_FinishUpload_Response)(nil)
	}
	r := new(CPartnerApps_FinishUpload_Response)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FinishUpload_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FinishUploadDepot_Request) CloneVT() *CPartnerApps_FinishUploadDepot_Request {
	if m == nil {
		return (*CPartnerApps_FinishUploadDepot_Request)(nil)
	}
	r := new(CPartnerApps_FinishUploadDepot_Request)
	r.UploadToken = protobuf_go_lite.ClonePtr(m.UploadToken)
	r.RoutingId = protobuf_go_lite.ClonePtr(m.RoutingId)
	r.AppId = protobuf_go_lite.ClonePtr(m.AppId)
	r.DepotId = protobuf_go_lite.ClonePtr(m.DepotId)
	r.BuildFlags = protobuf_go_lite.ClonePtr(m.BuildFlags)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FinishUploadDepot_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FinishUploadDepot_Response) CloneVT() *CPartnerApps_FinishUploadDepot_Response {
	if m == nil {
		return (*CPartnerApps_FinishUploadDepot_Response)(nil)
	}
	r := new(CPartnerApps_FinishUploadDepot_Response)
	r.BuildRoutingId = protobuf_go_lite.ClonePtr(m.BuildRoutingId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FinishUploadDepot_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_GetDepotBuildResult_Request) CloneVT() *CPartnerApps_GetDepotBuildResult_Request {
	if m == nil {
		return (*CPartnerApps_GetDepotBuildResult_Request)(nil)
	}
	r := new(CPartnerApps_GetDepotBuildResult_Request)
	r.UploadToken = protobuf_go_lite.ClonePtr(m.UploadToken)
	r.RoutingId = protobuf_go_lite.ClonePtr(m.RoutingId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_GetDepotBuildResult_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_GetDepotBuildResult_Response) CloneVT() *CPartnerApps_GetDepotBuildResult_Response {
	if m == nil {
		return (*CPartnerApps_GetDepotBuildResult_Response)(nil)
	}
	r := new(CPartnerApps_GetDepotBuildResult_Response)
	r.ManifestId = protobuf_go_lite.ClonePtr(m.ManifestId)
	r.ErrorMsg = protobuf_go_lite.ClonePtr(m.ErrorMsg)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_GetDepotBuildResult_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FindDRMUploads_Request) CloneVT() *CPartnerApps_FindDRMUploads_Request {
	if m == nil {
		return (*CPartnerApps_FindDRMUploads_Request)(nil)
	}
	r := new(CPartnerApps_FindDRMUploads_Request)
	r.AppId = protobuf_go_lite.ClonePtr(m.AppId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FindDRMUploads_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_ExistingDRMUpload) CloneVT() *CPartnerApps_ExistingDRMUpload {
	if m == nil {
		return (*CPartnerApps_ExistingDRMUpload)(nil)
	}
	r := new(CPartnerApps_ExistingDRMUpload)
	r.FileId = protobuf_go_lite.ClonePtr(m.FileId)
	r.AppId = protobuf_go_lite.ClonePtr(m.AppId)
	r.ActorId = protobuf_go_lite.ClonePtr(m.ActorId)
	r.SuppliedName = protobuf_go_lite.ClonePtr(m.SuppliedName)
	r.Flags = protobuf_go_lite.ClonePtr(m.Flags)
	r.ModType = protobuf_go_lite.ClonePtr(m.ModType)
	r.Timestamp = protobuf_go_lite.ClonePtr(m.Timestamp)
	r.OrigFileId = protobuf_go_lite.ClonePtr(m.OrigFileId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_ExistingDRMUpload) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_FindDRMUploads_Response) CloneVT() *CPartnerApps_FindDRMUploads_Response {
	if m == nil {
		return (*CPartnerApps_FindDRMUploads_Response)(nil)
	}
	r := new(CPartnerApps_FindDRMUploads_Response)
	r.Uploads = protobuf_go_lite.CloneVTSlice(m.Uploads)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_FindDRMUploads_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_Download_Request) CloneVT() *CPartnerApps_Download_Request {
	if m == nil {
		return (*CPartnerApps_Download_Request)(nil)
	}
	r := new(CPartnerApps_Download_Request)
	r.FileId = protobuf_go_lite.ClonePtr(m.FileId)
	r.AppId = protobuf_go_lite.ClonePtr(m.AppId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_Download_Request) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (m *CPartnerApps_Download_Response) CloneVT() *CPartnerApps_Download_Response {
	if m == nil {
		return (*CPartnerApps_Download_Response)(nil)
	}
	r := new(CPartnerApps_Download_Response)
	r.DownloadUrl = protobuf_go_lite.ClonePtr(m.DownloadUrl)
	r.AppId = protobuf_go_lite.ClonePtr(m.AppId)
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CPartnerApps_Download_Response) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *CPartnerApps_RequestUploadToken_Request) EqualVT(that *CPartnerApps_RequestUploadToken_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Filename, that.Filename) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Appid, that.Appid) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_RequestUploadToken_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_RequestUploadToken_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_RequestUploadToken_Response) EqualVT(that *CPartnerApps_RequestUploadToken_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.UploadToken, that.UploadToken) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Location, that.Location) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.RoutingId, that.RoutingId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_RequestUploadToken_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_RequestUploadToken_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FinishUpload_Request) EqualVT(that *CPartnerApps_FinishUpload_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.UploadToken, that.UploadToken) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.RoutingId, that.RoutingId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AppId, that.AppId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FinishUpload_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FinishUpload_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FinishUploadKVSign_Response) EqualVT(that *CPartnerApps_FinishUploadKVSign_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.SignedInstallscript, that.SignedInstallscript) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FinishUploadKVSign_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FinishUploadKVSign_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FinishUploadLegacyDRM_Request) EqualVT(that *CPartnerApps_FinishUploadLegacyDRM_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.UploadToken, that.UploadToken) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.RoutingId, that.RoutingId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AppId, that.AppId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Flags, that.Flags) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.ToolName, that.ToolName) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.UseCloud, that.UseCloud) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FinishUploadLegacyDRM_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FinishUploadLegacyDRM_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FinishUploadLegacyDRM_Response) EqualVT(that *CPartnerApps_FinishUploadLegacyDRM_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.FileId, that.FileId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FinishUploadLegacyDRM_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FinishUploadLegacyDRM_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FinishUpload_Response) EqualVT(that *CPartnerApps_FinishUpload_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FinishUpload_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FinishUpload_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FinishUploadDepot_Request) EqualVT(that *CPartnerApps_FinishUploadDepot_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.UploadToken, that.UploadToken) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.RoutingId, that.RoutingId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AppId, that.AppId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DepotId, that.DepotId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.BuildFlags, that.BuildFlags) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FinishUploadDepot_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FinishUploadDepot_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FinishUploadDepot_Response) EqualVT(that *CPartnerApps_FinishUploadDepot_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.BuildRoutingId, that.BuildRoutingId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FinishUploadDepot_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FinishUploadDepot_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_GetDepotBuildResult_Request) EqualVT(that *CPartnerApps_GetDepotBuildResult_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.UploadToken, that.UploadToken) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.RoutingId, that.RoutingId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_GetDepotBuildResult_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_GetDepotBuildResult_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_GetDepotBuildResult_Response) EqualVT(that *CPartnerApps_GetDepotBuildResult_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.ManifestId, that.ManifestId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.ErrorMsg, that.ErrorMsg) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_GetDepotBuildResult_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_GetDepotBuildResult_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FindDRMUploads_Request) EqualVT(that *CPartnerApps_FindDRMUploads_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AppId, that.AppId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FindDRMUploads_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FindDRMUploads_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_ExistingDRMUpload) EqualVT(that *CPartnerApps_ExistingDRMUpload) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.FileId, that.FileId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AppId, that.AppId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.ActorId, that.ActorId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.SuppliedName, that.SuppliedName) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Flags, that.Flags) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.ModType, that.ModType) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.Timestamp, that.Timestamp) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.OrigFileId, that.OrigFileId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_ExistingDRMUpload) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_ExistingDRMUpload)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_FindDRMUploads_Response) EqualVT(that *CPartnerApps_FindDRMUploads_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualVTSliceImplicit(this.Uploads, that.Uploads, func() *CPartnerApps_ExistingDRMUpload { return &CPartnerApps_ExistingDRMUpload{} }) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_FindDRMUploads_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_FindDRMUploads_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_Download_Request) EqualVT(that *CPartnerApps_Download_Request) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.FileId, that.FileId) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AppId, that.AppId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_Download_Request) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_Download_Request)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

func (this *CPartnerApps_Download_Response) EqualVT(that *CPartnerApps_Download_Response) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.DownloadUrl, that.DownloadUrl) {
		return false
	}
	if !protobuf_go_lite.EqualPtr(this.AppId, that.AppId) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CPartnerApps_Download_Response) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CPartnerApps_Download_Response)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *CPartnerApps_RequestUploadToken_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_RequestUploadToken_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_RequestUploadToken_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.Appid != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Appid))
		i--
		dAtA[i] = 0x10
	}
	if m.Filename != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.Filename)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_RequestUploadToken_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_RequestUploadToken_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_RequestUploadToken_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.RoutingId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.RoutingId))
		i--
		dAtA[i] = 0x18
	}
	if m.Location != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.Location)
		i--
		dAtA[i] = 0x12
	}
	if m.UploadToken != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.UploadToken))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FinishUpload_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FinishUpload_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FinishUpload_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.AppId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AppId))
		i--
		dAtA[i] = 0x18
	}
	if m.RoutingId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.RoutingId))
		i--
		dAtA[i] = 0x10
	}
	if m.UploadToken != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.UploadToken))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FinishUploadKVSign_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FinishUploadKVSign_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FinishUploadKVSign_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.SignedInstallscript != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.SignedInstallscript)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.UseCloud != nil {
		i = protobuf_go_lite.EncodeBool(dAtA, i, *m.UseCloud)
		i--
		dAtA[i] = 0x30
	}
	if m.ToolName != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.ToolName)
		i--
		dAtA[i] = 0x2a
	}
	if m.Flags != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Flags))
		i--
		dAtA[i] = 0x20
	}
	if m.AppId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AppId))
		i--
		dAtA[i] = 0x18
	}
	if m.RoutingId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.RoutingId))
		i--
		dAtA[i] = 0x10
	}
	if m.UploadToken != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.UploadToken))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.FileId != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.FileId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FinishUpload_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FinishUpload_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FinishUpload_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FinishUploadDepot_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FinishUploadDepot_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FinishUploadDepot_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.BuildFlags != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.BuildFlags))
		i--
		dAtA[i] = 0x28
	}
	if m.DepotId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.DepotId))
		i--
		dAtA[i] = 0x20
	}
	if m.AppId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AppId))
		i--
		dAtA[i] = 0x18
	}
	if m.RoutingId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.RoutingId))
		i--
		dAtA[i] = 0x10
	}
	if m.UploadToken != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.UploadToken))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FinishUploadDepot_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FinishUploadDepot_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FinishUploadDepot_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.BuildRoutingId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.BuildRoutingId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_GetDepotBuildResult_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_GetDepotBuildResult_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_GetDepotBuildResult_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.RoutingId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.RoutingId))
		i--
		dAtA[i] = 0x10
	}
	if m.UploadToken != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.UploadToken))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_GetDepotBuildResult_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_GetDepotBuildResult_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_GetDepotBuildResult_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.ErrorMsg != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.ErrorMsg)
		i--
		dAtA[i] = 0x12
	}
	if m.ManifestId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.ManifestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FindDRMUploads_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FindDRMUploads_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FindDRMUploads_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.AppId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_ExistingDRMUpload) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_ExistingDRMUpload) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_ExistingDRMUpload) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.OrigFileId != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.OrigFileId)
		i--
		dAtA[i] = 0x4a
	}
	if m.Timestamp != nil {
		i = protobuf_go_lite.EncodeFixed32(dAtA, i, uint32(*m.Timestamp))
		i--
		dAtA[i] = 0x45
	}
	if m.ModType != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.ModType)
		i--
		dAtA[i] = 0x3a
	}
	if m.Flags != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Flags))
		i--
		dAtA[i] = 0x30
	}
	if m.SuppliedName != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.SuppliedName)
		i--
		dAtA[i] = 0x2a
	}
	if m.ActorId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.ActorId))
		i--
		dAtA[i] = 0x18
	}
	if m.AppId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AppId))
		i--
		dAtA[i] = 0x10
	}
	if m.FileId != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.FileId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_FindDRMUploads_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_FindDRMUploads_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_FindDRMUploads_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if len(m.Uploads) > 0 {
		for iNdEx := len(m.Uploads) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Uploads[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_Download_Request) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_Download_Request) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_Download_Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.AppId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AppId))
		i--
		dAtA[i] = 0x10
	}
	if m.FileId != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.FileId)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_Download_Response) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPartnerApps_Download_Response) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CPartnerApps_Download_Response) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i = protobuf_go_lite.EncodeRawBytes(dAtA, i, m.unknownFields)
	}
	if m.AppId != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.AppId))
		i--
		dAtA[i] = 0x10
	}
	if m.DownloadUrl != nil {
		i = protobuf_go_lite.EncodeString(dAtA, i, *m.DownloadUrl)
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CPartnerApps_RequestUploadToken_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.Filename)
	n += protobuf_go_lite.SizeVarintPtr(1, m.Appid)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_RequestUploadToken_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.UploadToken)
	n += protobuf_go_lite.SizeStringPtr(1, m.Location)
	n += protobuf_go_lite.SizeVarintPtr(1, m.RoutingId)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FinishUpload_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.UploadToken)
	n += protobuf_go_lite.SizeVarintPtr(1, m.RoutingId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.AppId)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FinishUploadKVSign_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.SignedInstallscript)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.UploadToken)
	n += protobuf_go_lite.SizeVarintPtr(1, m.RoutingId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.AppId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.Flags)
	n += protobuf_go_lite.SizeStringPtr(1, m.ToolName)
	n += protobuf_go_lite.SizeBoolPtr(1, m.UseCloud)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.FileId)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FinishUpload_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FinishUploadDepot_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.UploadToken)
	n += protobuf_go_lite.SizeVarintPtr(1, m.RoutingId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.AppId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.DepotId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.BuildFlags)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FinishUploadDepot_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.BuildRoutingId)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_GetDepotBuildResult_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.UploadToken)
	n += protobuf_go_lite.SizeVarintPtr(1, m.RoutingId)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_GetDepotBuildResult_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.ManifestId)
	n += protobuf_go_lite.SizeStringPtr(1, m.ErrorMsg)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FindDRMUploads_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeVarintPtr(1, m.AppId)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_ExistingDRMUpload) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.FileId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.AppId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.ActorId)
	n += protobuf_go_lite.SizeStringPtr(1, m.SuppliedName)
	n += protobuf_go_lite.SizeVarintPtr(1, m.Flags)
	n += protobuf_go_lite.SizeStringPtr(1, m.ModType)
	n += protobuf_go_lite.SizeFixed32Ptr(1, m.Timestamp)
	n += protobuf_go_lite.SizeStringPtr(1, m.OrigFileId)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_FindDRMUploads_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	for _, e := range m.Uploads {
		l = e.SizeVT()
		n += protobuf_go_lite.SizeMessage(1, l)
	}
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_Download_Request) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.FileId)
	n += protobuf_go_lite.SizeVarintPtr(1, m.AppId)
	n += len(m.unknownFields)
	return n
}

func (m *CPartnerApps_Download_Response) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += protobuf_go_lite.SizeStringPtr(1, m.DownloadUrl)
	n += protobuf_go_lite.SizeVarintPtr(1, m.AppId)
	n += len(m.unknownFields)
	return n
}

func (x *CPartnerApps_RequestUploadToken_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_RequestUploadToken_Request")
	if x.Filename != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "filename")
		protobuf_go_lite.TextWriteString(&sb, *x.Filename)
	}
	if x.Appid != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "appid")
		protobuf_go_lite.TextWriteUint(&sb, *x.Appid)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_RequestUploadToken_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_RequestUploadToken_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_RequestUploadToken_Response")
	if x.UploadToken != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "upload_token")
		protobuf_go_lite.TextWriteUint(&sb, *x.UploadToken)
	}
	if x.Location != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "location")
		protobuf_go_lite.TextWriteString(&sb, *x.Location)
	}
	if x.RoutingId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "routing_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.RoutingId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_RequestUploadToken_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FinishUpload_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FinishUpload_Request")
	if x.UploadToken != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "upload_token")
		protobuf_go_lite.TextWriteUint(&sb, *x.UploadToken)
	}
	if x.RoutingId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "routing_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.RoutingId)
	}
	if x.AppId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "app_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.AppId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FinishUpload_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FinishUploadKVSign_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FinishUploadKVSign_Response")
	if x.SignedInstallscript != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "signed_installscript")
		protobuf_go_lite.TextWriteString(&sb, *x.SignedInstallscript)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FinishUploadKVSign_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FinishUploadLegacyDRM_Request")
	if x.UploadToken != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "upload_token")
		protobuf_go_lite.TextWriteUint(&sb, *x.UploadToken)
	}
	if x.RoutingId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "routing_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.RoutingId)
	}
	if x.AppId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "app_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.AppId)
	}
	if x.Flags != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "flags")
		protobuf_go_lite.TextWriteUint(&sb, *x.Flags)
	}
	if x.ToolName != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "tool_name")
		protobuf_go_lite.TextWriteString(&sb, *x.ToolName)
	}
	if x.UseCloud != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "use_cloud")
		protobuf_go_lite.TextWriteBool(&sb, *x.UseCloud)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FinishUploadLegacyDRM_Response")
	if x.FileId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "file_id")
		protobuf_go_lite.TextWriteString(&sb, *x.FileId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FinishUploadLegacyDRM_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FinishUpload_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FinishUpload_Response")
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FinishUpload_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FinishUploadDepot_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FinishUploadDepot_Request")
	if x.UploadToken != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "upload_token")
		protobuf_go_lite.TextWriteUint(&sb, *x.UploadToken)
	}
	if x.RoutingId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "routing_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.RoutingId)
	}
	if x.AppId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "app_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.AppId)
	}
	if x.DepotId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "depot_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.DepotId)
	}
	if x.BuildFlags != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "build_flags")
		protobuf_go_lite.TextWriteUint(&sb, *x.BuildFlags)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FinishUploadDepot_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FinishUploadDepot_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FinishUploadDepot_Response")
	if x.BuildRoutingId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "build_routing_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.BuildRoutingId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FinishUploadDepot_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_GetDepotBuildResult_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_GetDepotBuildResult_Request")
	if x.UploadToken != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "upload_token")
		protobuf_go_lite.TextWriteUint(&sb, *x.UploadToken)
	}
	if x.RoutingId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "routing_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.RoutingId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_GetDepotBuildResult_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_GetDepotBuildResult_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_GetDepotBuildResult_Response")
	if x.ManifestId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "manifest_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.ManifestId)
	}
	if x.ErrorMsg != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "error_msg")
		protobuf_go_lite.TextWriteString(&sb, *x.ErrorMsg)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_GetDepotBuildResult_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FindDRMUploads_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FindDRMUploads_Request")
	if x.AppId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "app_id")
		protobuf_go_lite.TextWriteInt(&sb, *x.AppId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FindDRMUploads_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_ExistingDRMUpload) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_ExistingDRMUpload")
	if x.FileId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "file_id")
		protobuf_go_lite.TextWriteString(&sb, *x.FileId)
	}
	if x.AppId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "app_id")
		protobuf_go_lite.TextWriteUint(&sb, *x.AppId)
	}
	if x.ActorId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "actor_id")
		protobuf_go_lite.TextWriteInt(&sb, *x.ActorId)
	}
	if x.SuppliedName != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "supplied_name")
		protobuf_go_lite.TextWriteString(&sb, *x.SuppliedName)
	}
	if x.Flags != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "flags")
		protobuf_go_lite.TextWriteUint(&sb, *x.Flags)
	}
	if x.ModType != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "mod_type")
		protobuf_go_lite.TextWriteString(&sb, *x.ModType)
	}
	if x.Timestamp != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "timestamp")
		protobuf_go_lite.TextWriteUint(&sb, *x.Timestamp)
	}
	if x.OrigFileId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "orig_file_id")
		protobuf_go_lite.TextWriteString(&sb, *x.OrigFileId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_ExistingDRMUpload) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_FindDRMUploads_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_FindDRMUploads_Response")
	if len(x.Uploads) > 0 {
		protobuf_go_lite.TextWriteListStart(&sb, initialLen, "uploads")
		for i, v := range x.Uploads {
			protobuf_go_lite.TextWriteListSeparator(&sb, i)
			if v == nil {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, &CPartnerApps_ExistingDRMUpload{})
			} else {
				protobuf_go_lite.TextWriteTextMarshaler(&sb, v)
			}
		}
		protobuf_go_lite.TextWriteListEnd(&sb)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_FindDRMUploads_Response) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_Download_Request) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_Download_Request")
	if x.FileId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "file_id")
		protobuf_go_lite.TextWriteString(&sb, *x.FileId)
	}
	if x.AppId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "app_id")
		protobuf_go_lite.TextWriteInt(&sb, *x.AppId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_Download_Request) String() string {
	return x.MarshalProtoText()
}

func (x *CPartnerApps_Download_Response) MarshalProtoText() string {
	var sb protobuf_go_lite.TextBuilder
	initialLen := protobuf_go_lite.TextStartMessage(&sb, "CPartnerApps_Download_Response")
	if x.DownloadUrl != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "download_url")
		protobuf_go_lite.TextWriteString(&sb, *x.DownloadUrl)
	}
	if x.AppId != nil {
		protobuf_go_lite.TextWriteFieldPrefix(&sb, initialLen, "app_id")
		protobuf_go_lite.TextWriteInt(&sb, *x.AppId)
	}
	return protobuf_go_lite.TextFinishMessage(&sb)
}

func (x *CPartnerApps_Download_Response) String() string {
	return x.MarshalProtoText()
}

func (m *CPartnerApps_RequestUploadToken_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_RequestUploadToken_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_RequestUploadToken_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filename", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Filename = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Appid", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Appid = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_RequestUploadToken_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_RequestUploadToken_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_RequestUploadToken_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadToken", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.UploadToken = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Location = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.RoutingId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FinishUpload_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FinishUpload_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FinishUpload_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadToken", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.UploadToken = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.RoutingId = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AppId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FinishUploadKVSign_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadKVSign_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadKVSign_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedInstallscript", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SignedInstallscript = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadLegacyDRM_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadLegacyDRM_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadToken", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.UploadToken = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.RoutingId = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AppId = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Flags = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToolName", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ToolName = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UseCloud", wireType)
			}
			var v bool
			v, iNdEx, err = protobuf_go_lite.DecodeVarintBool(dAtA, iNdEx)
			if err != nil {
				return err
			}
			b := bool(v)
			m.UseCloud = &b
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadLegacyDRM_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadLegacyDRM_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.FileId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FinishUpload_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FinishUpload_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FinishUpload_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FinishUploadDepot_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadDepot_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadDepot_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadToken", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.UploadToken = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.RoutingId = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AppId = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepotId", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DepotId = &v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuildFlags", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.BuildFlags = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FinishUploadDepot_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadDepot_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FinishUploadDepot_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuildRoutingId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.BuildRoutingId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_GetDepotBuildResult_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_GetDepotBuildResult_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_GetDepotBuildResult_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadToken", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.UploadToken = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.RoutingId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_GetDepotBuildResult_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_GetDepotBuildResult_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_GetDepotBuildResult_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ManifestId", wireType)
			}
			var v uint64
			v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ManifestId = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMsg", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ErrorMsg = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FindDRMUploads_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FindDRMUploads_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FindDRMUploads_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AppId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_ExistingDRMUpload) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_ExistingDRMUpload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_ExistingDRMUpload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.FileId = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AppId = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActorId", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ActorId = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuppliedName", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.SuppliedName = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Flags = &v
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModType", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.ModType = &v
		case 8:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint32
			var _v32 uint32
			_v32, iNdEx, err = protobuf_go_lite.DecodeFixed32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			v = uint32(_v32)
			m.Timestamp = &v
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigFileId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.OrigFileId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_FindDRMUploads_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_FindDRMUploads_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_FindDRMUploads_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uploads", wireType)
			}
			msgStart, postIndex, err := protobuf_go_lite.DecodeLengthDelimited(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Uploads = append(m.Uploads, &CPartnerApps_ExistingDRMUpload{})
			if err := m.Uploads[len(m.Uploads)-1].UnmarshalVT(dAtA[msgStart:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_Download_Request) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_Download_Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_Download_Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileId", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.FileId = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AppId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CPartnerApps_Download_Response) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPartnerApps_Download_Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPartnerApps_Download_Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownloadUrl", wireType)
			}
			var v string
			v, iNdEx, err = protobuf_go_lite.DecodeString(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.DownloadUrl = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			var v int32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintInt32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.AppId = &v
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
